// 1. UNIQUE ITEM EMOJI REGISTRY
export const ITEM_EMOJIS = {
    // --- FRUITS ---
    'apple': '🍎', 'banana': '🍌', 'strawberry': '🍓', 'blueberry': '🫐', 'cherry': '🍒',
    'lemon': '🍋', 'lime': '🍋', 'orange': '🍊', 'citrus': '🍊', 'melon': '🍈', 
    'watermelon': '🍉', 'avocado': '🥑', 'grape': '🍇', 'peach': '🍑', 'kiwi': '🥝', 'mango': '🥭',
  
    // --- VEGETABLES ---
    'potato': '🥔', 'carrot': '🥕', 'broccoli': '🥦', 'tomato': '🍅', 'onion': '🧅', 
    'garlic': '🧄', 'cucumber': '🥒', 'pepper': '🫑', 'corn': '🌽', 'mushroom': '🍄', 
    'cabbage': '🥬', 'lettuce': '🥬', 'spinach': '🥬', 'zucchini': '🥒', 'eggplant': '🍆',
  
    // --- MEAT & SEAFOOD ---
    'chicken': '🍗', 'turkey': '🦃', 'wing': '🍗', 'drumstick': '🍗', 'breast': '🥩',
    'beef': '🥩', 'steak': '🥩', 'mince': '🥩', 'burger': '🍔', 'lamb': '🥩',
    'pork': '🥓', 'bacon': '🥓', 'sausage': '🌭', 'pepperoni': '🍕', 'salami': '🥓', 'ham': '🍖',
    'salmon': '🐟', 'fish': '🐟', 'tuna': '🐟', 'shrimp': '🍤', 'prawn': '🍤', 'crab': '🦀', 'lobster': '🦞',
  
    // --- DAIRY & REFRIGERATED ---
    'milk': '🥛', 'butter': '🧈', 'cream': '🥛', 'yogurt': '🥛', 'ayran': '🥛', 'cacik': '🥣',
    'egg': '🥚', 'cheese': '🧀', 'cheddar': '🧀', 'mozzarella': '🧀', 'feta': '🧀', 'kasar': '🧀', 'peynir': '🧀',
    'almond milk': '🌱', 'oat milk': '🌱', 'soy milk': '🌱',
  
    // --- PANTRY STAPLES ---
    'rice': '🍚', 'oat': '🥣', 'quinoa': '🥣', 'bread': '🍞', 'tortilla': '🫓', 'flour': '🌾', 
    'sugar': '🍬', 'pasta': '🍝', 'spaghetti': '🍝', 'macaroni': '🍝', 'noodle': '🍜',
    'soup': '🥣', 'bean': '🫘', 'sauce': '🥫', 'paste': '🥫', 'canned': '🥫',
    'oil': '🍾', 'olive oil': '🫒', 'vinegar': '🍾', 'mayo': '🍾', 'ketchup': '🍅', 'mustard': '🍾',
    'salt': '🧂', 'pepper': '🧂', 'spice': '🌶️',
  
    // --- SNACKS & TREATS ---
    'chip': '🥔', 'nut': '🥜', 'popcorn': '🍿', 'cracker': '🫓', 'cookie': '🍪', 
    'chocolate': '🍫', 'biscuit': '🍪', 'sweet': '🍬', 'candy': '🍬', 'ice cream': '🍦', 'popsicle': '🍧',
  
    // --- BEVERAGES ---
    'coffee': '☕', 'bean': '🫘', 'tea': '🍵', 'cai': '🍵', 'espresso': '☕', 'hot chocolate': '☕',
    'water': '💧', 'juice': '🧃', 'soda': '🥤', 'cola': '🥤', 'sprite': '🥤', 'fanta': '🥤',
    'beer': '🍺', 'wine': '🍷', 'vodka': '🍾', 'whiskey': '🥃', 'raki': '🥛',
  
    // --- HOUSEHOLD & PET ---
    'toilet paper': '🧻', 'paper towel': '🧻', 'napkin': '🧻', 'tissue': '🧻',
    'soap': '🧼', 'detergent': '🧼', 'spray': '🧴', 'cleaner': '🧼', 'bleach': '🧴', 'sponge': '🧽',
    'shampoo': '🧴', 'toothpaste': '🪥', 'deodorant': '🧴', 'bandage': '🩹', 'medicine': '💊', 'vitamin': '💊',
    'cat food': '🐱', 'dog food': '🐶', 'pet': '🐾', 'treats': '🦴'
  };
  export const PREDEFINED_ITEMS = [
    { label: "🥛 2% Milk", name: "2% Milk" },
    { label: "🧃 Apple juice", name: "Apple juice" },
    { label: "🌾 All-purpose flour", name: "All-purpose flour" },
    { label: "🌱 Almond butter", name: "Almond butter" },
    { label: "🌾 Almond flour", name: "Almond flour" },
    { label: "🌱 Almond milk", name: "Almond milk" },
    { label: "🧴 Aluminum foil", name: "Aluminum foil" },
    { label: "🧴 All-purpose cleaner spray", name: "All-purpose cleaner spray" },
    { label: "🥫 Anchovies", name: "Anchovies" },
    { label: "🧴 Antiperspirant", name: "Antiperspirant" },
    { label: "🍚 Arborio rice", name: "Arborio rice" },
    { label: "🥬 Arugula", name: "Arugula" },
    { label: "🐟 Atlantic salmon", name: "Atlantic salmon" },
    { label: "🥑 Avocado oil", name: "Avocado oil" },
    { label: "🧴 Baby formula", name: "Baby formula" },
    { label: "🧴 Baby food jars", name: "Baby food jars" },
    { label: "🧴 Baby lotion", name: "Baby lotion" },
    { label: "🧴 Baby shampoo", name: "Baby shampoo" },
    { label: "🧴 Baby wipes", name: "Baby wipes" },
    { label: "🥓 Bacon", name: "Bacon" },
    { label: "🥫 Baked beans", name: "Baked beans" },
    { label: "🌾 Baking powder", name: "Baking powder" },
    { label: "🌾 Baking soda", name: "Baking soda" },
    { label: "🍾 Balsamic vinegar", name: "Balsamic vinegar" },
    { label: "🍌 Bananas", name: "Bananas" },
    { label: "🧴 Bar soap", name: "Bar soap" },
    { label: "🔥 Barbecue sauce", name: "Barbecue sauce" },
    { label: "🥣 Barley", name: "Barley" },
    { label: "🍐 Bartlett pears", name: "Bartlett pears" },
    { label: "🍚 Basmati rice", name: "Basmati rice" },
    { label: "🌿 Basil", name: "Basil" },
    { label: "🫘 Black beans", name: "Black beans" },
    { label: "🥩 Beef chuck roast", name: "Beef chuck roast" },
    { label: "🥣 Beef broth", name: "Beef broth" },
    { label: "🥩 Beef stew meat", name: "Beef stew meat" },
    { label: "🫘 Beets", name: "Beets" },
    { label: "🍺 Beer", name: "Beer" },
    { label: "🫑 Bell peppers", name: "Bell peppers" },
    { label: "🍪 Biscuit", name: "Biscuit" },
    { label: "🍪 Brownies", name: "Brownies" },
    { label: "🍇 Blackberries", name: "Blackberries" },
    { label: "🧂 Black peppercorns", name: "Black peppercorns" },
    { label: "🍵 Black tea bags", name: "Black tea bags" },
    { label: "🍊 Blood oranges", name: "Blood oranges" },
    { label: "🫐 Blueberries", name: "Blueberries" },
    { label: "🧀 Blue cheese", name: "Blue cheese" },
    { label: "🦪 Blue mussels", name: "Blue mussels" },
    { label: "🥦 Bok choy", name: "Bok choy" },
    { label: "🥩 Bologna", name: "Bologna" },
    { label: "🧴 Body lotion", name: "Body lotion" },
    { label: "🧴 Body wash", name: "Body wash" },
    { label: "💧 Bottled spring water", name: "Bottled spring water" },
    { label: "🧀 Brie", name: "Brie" },
    { label: "🥦 Broccoli", name: "Broccoli" },
    { label: "🥦 Broccolini", name: "Broccolini" },
    { label: "🍚 Brown rice", name: "Brown rice" },
    { label: "🌾 Brown sugar", name: "Brown sugar" },
    { label: "🥦 Brussels sprouts", name: "Brussels sprouts" },
    { label: "🛁 Bubble bath", name: "Bubble bath" },
    { label: "🥛 Buttermilk", name: "Buttermilk" },
    { label: "🥬 Cabbage", name: "Cabbage" },
    { label: "🥫 Canned albacore tuna", name: "Canned albacore tuna" },
    { label: "🥫 Canned chicken breast", name: "Canned chicken breast" },
    { label: "🥫 Canned salmon", name: "Canned salmon" },
    { label: "🍉 Cantaloupe", name: "Cantaloupe" },
    { label: "🫘 Carrots", name: "Carrots" },
    { label: "🌱 Cashew milk", name: "Cashew milk" },
    { label: "🥜 Cashews", name: "Cashews" },
    { label: "🐱 Cat food", name: "Cat food" },
    { label: "🐾 Cat litter", name: "Cat litter" },
    { label: "🦴 Cat treats", name: "Cat treats" },
    { label: "🥦 Cauliflower", name: "Cauliflower" },
    { label: "🌶️ Cayenne pepper", name: "Cayenne pepper" },
    { label: "🥬 Celery", name: "Celery" },
    { label: "🍵 Chamomile tea", name: "Chamomile tea" },
    { label: "🧀 Sharp cheddar", name: "Sharp cheddar" },
    { label: "🍒 Cherries", name: "Cherries" },
    { label: "🍅 Cherry tomatoes", name: "Cherry tomatoes" },
    { label: "🫘 Chia seeds", name: "Chia seeds" },
    { label: "🍗 Chicken breasts", name: "Chicken breasts" },
    { label: "🥣 Chicken broth", name: "Chicken broth" },
    { label: "🥫 Chicken noodle soup", name: "Chicken noodle soup" },
    { label: "🍗 Chicken nuggets", name: "Chicken nuggets" },
    { label: "🍗 Chicken thighs", name: "Chicken thighs" },
    { label: "🍗 Chicken wings", name: "Chicken wings" },
    { label: "🌶️ Chili powder", name: "Chili powder" },
    { label: "🍫 Chocolate chip cookies", name: "Chocolate chip cookies" },
    { label: "🍫 Chocolate chips", name: "Chocolate chips" },
    { label: "🍦 Chocolate ice cream", name: "Chocolate ice cream" },
    { label: "🌿 Cilantro", name: "Cilantro" },
    { label: "🌿 Chives", name: "Chives" },
    { label: "🦪 Clams", name: "Clams" },
    { label: "🍊 Clementines", name: "Clementines" },
    { label: "🌾 Cocoa powder", name: "Cocoa powder" },
    { label: "🥥 Coconut milk", name: "Coconut milk" },
    { label: "🥥 Coconut oil", name: "Coconut oil" },
    { label: "🥥 Coconuts", name: "Coconuts" },
    { label: "🐟 Cod fillets", name: "Cod fillets" },
    { label: "☕ Coffee beans", name: "Coffee beans" },
    { label: "🥬 Collard greens", name: "Collard greens" },
    { label: "🥛 Condensed milk", name: "Condensed milk" },
    { label: "🧴 Conditioner", name: "Conditioner" },
    { label: "🍪 Cookie dough", name: "Cookie dough" },
    { label: "🍿 Corn chips", name: "Corn chips" },
    { label: "🍿 Cornflakes", name: "Cornflakes" },
    { label: "🌾 Cornstarch", name: "Cornstarch" },
    { label: "🧴 Cotton pads", name: "Cotton pads" },
    { label: "🧀 Cottage cheese", name: "Cottage cheese" },
    { label: "🥣 Couscous", name: "Couscous" },
    { label: "🦪 Crab meat", name: "Crab meat" },
    { label: "🧃 Cranberry juice", name: "Cranberry juice" },
    { label: "🧀 Cream cheese", name: "Cream cheese" },
    { label: "🌱 Creamy peanut butter", name: "Creamy peanut butter" },
    { label: "🥛 Crème fraîche", name: "Crème fraîche" },
    { label: "🍿 Crunchy peanut butter", name: "Crunchy peanut butter" },
    { label: "🥫 Crushed tomatoes", name: "Crushed tomatoes" },
    { label: "🌶️ Crushed red pepper flakes", name: "Crushed red pepper flakes" },
    { label: "🥒 Cucumber", name: "Cucumber" },
    { label: "🌶️ Curry powder", name: "Curry powder" },
    { label: "🍫 Dark chocolate", name: "Dark chocolate" },
    { label: "🥩 Deli ham", name: "Deli ham" },
    { label: "🧴 Dental floss", name: "Dental floss" },
    { label: "🧴 Deodorant", name: "Deodorant" },
    { label: "🥫 Diced tomatoes", name: "Diced tomatoes" },
    { label: "🥤 Diet soda", name: "Diet soda" },
    { label: "🧴 Diapers", name: "Diapers" },
    { label: "🍾 Dijon mustard", name: "Dijon mustard" },
    { label: "🌿 Dill", name: "Dill" },
    { label: "🧼 Disinfecting wipes", name: "Disinfecting wipes" },
    { label: "🧼 Dishwasher pods", name: "Dishwasher pods" },
    { label: "🧴 Disposable razors", name: "Disposable razors" },
    { label: "🐾 Dog treats", name: "Dog treats" },
    { label: "🌿 Dried basil", name: "Dried basil" },
    { label: "🌿 Dried oregano", name: "Dried oregano" },
    { label: "🌿 Dried thyme", name: "Dried thyme" },
    { label: "🐶 Dry dog food", name: "Dry dog food" },
    { label: "🐱 Dry cat food", name: "Dry cat food" },
    { label: "🧼 Dryer sheets", name: "Dryer sheets" },
    { label: "🧼 Duster refills", name: "Duster refills" },
    { label: "🫘 Edamame", name: "Edamame" },
    { label: "🥚 Eggplant", name: "Eggplant" },
    { label: "🍝 Elbow macaroni", name: "Elbow macaroni" },
    { label: "🥤 Energy drinks", name: "Energy drinks" },
    { label: "🧂 Everything bagel seasoning", name: "Everything bagel seasoning" },
    { label: "🌱 Firm tofu", name: "Firm tofu" },
    { label: "🌱 Extra-firm tofu", name: "Extra-firm tofu" },
    { label: "🍾 Extra virgin olive oil", name: "Extra virgin olive oil" },
    { label: "🧴 Facial cleanser", name: "Facial cleanser" },
    { label: "🧻 Facial tissues", name: "Facial tissues" },
    { label: "🧼 Fabric softener", name: "Fabric softener" },
    { label: "🥣 Farro", name: "Farro" },
    { label: "🧀 Feta", name: "Feta" },
    { label: "🍝 Fettuccine", name: "Fettuccine" },
    { label: "🧂 Fine sea salt", name: "Fine sea salt" },
    { label: "🐟 Fish sauce", name: "Fish sauce" },
    { label: "🌿 Flat-leaf parsley", name: "Flat-leaf parsley" },
    { label: "🥩 Flank steak", name: "Flank steak" },
    { label: "🫘 Flaxseeds", name: "Flaxseeds" },
    { label: "🧼 Floor cleaning solution", name: "Floor cleaning solution" },
    { label: "🧴 Fluoride toothpaste", name: "Whitening toothpaste" },
    { label: "🍟 French fries", name: "French fries" },
    { label: "🥦 Frozen broccoli florets", name: "Frozen broccoli florets" },
    { label: "🫐 Frozen blueberries", name: "Frozen blueberries" },
    { label: "🍕 Frozen pizza", name: "Frozen pizza" },
    { label: "🌯 Frozen burritos", name: "Frozen burritos" },
    { label: "🌽 Frozen corn", name: "Frozen corn" },
    { label: "🥭 Frozen mango chunks", name: "Frozen mango chunks" },
    { label: "🥦 Frozen mixed vegetables", name: "Frozen mixed vegetables" },
    { label: "🥦 Frozen peas", name: "Frozen peas" },
    { label: "🥬 Frozen riced cauliflower", name: "Frozen riced cauliflower" },
    { label: "🍓 Frozen strawberries", name: "Frozen strawberries" },
    { label: "🍦 Frozen waffles", name: "Frozen waffles" },
    { label: "🍦 Frozen yogurt", name: "Frozen yogurt" },
    { label: "🍇 Fruit popsicles", name: "Fruit popsicles" },
    { label: "🍓 Fruit snacks", name: "Fruit snacks" },
    { label: "🧻 Gallon ziploc bags", name: "Gallon ziploc bags" },
    { label: "🧄 Garlic", name: "Garlic" },
    { label: "🧂 Garlic powder", name: "Garlic powder" },
    { label: "🫘 Ginger", name: "Ginger" },
    { label: "🧼 Glass cleaner", name: "Glass cleaner" },
    { label: "🧀 Goat cheese", name: "Goat cheese" },
    { label: "🧀 Gouda", name: "Gouda" },
    { label: "🍇 Grapefruit", name: "Grapefruit" },
    { label: "🌱 Grape jelly", name: "Grape jelly" },
    { label: "🌾 Granulated sugar", name: "Granulated sugar" },
    { label: "🍿 Granola bars", name: "Granola bars" },
    { label: "🍏 Granny Smith apples", name: "Granny Smith apples" },
    { label: "🫘 Green beans", name: "Green beans" },
    { label: "🫘 Green lentils", name: "Green lentils" },
    { label: "🥦 Green peas", name: "Green peas" },
    { label: "🍵 Green tea", name: "Green tea" },
    { label: "🥩 Ground beef", name: "Ground beef" },
    { label: "☕ Ground coffee", name: "Ground coffee" },
    { label: "🥩 Ground pork", name: "Ground pork" },
    { label: "🥩 Ground turkey", name: "Ground turkey" },
    { label: "🌶️ Ground Cinnamon", name: "Ground Cinnamon" },
    { label: "🌶️ Ground cumin", name: "Ground cumin" },
    { label: "🌶️ Ground ginger", name: "Ground ginger" },
    { label: "🥑 Guacamole", name: "Guacamole" },
    { label: "🍫 Gummy bears", name: "Gummy bears" },
    { label: "🐟 Halibut", name: "Halibut" },
    { label: "🥛 Half-and-half", name: "Half-and-half" },
    { label: "🧴 Hand sanitizer", name: "Hand sanitizer" },
    { label: "🥔 Hash browns", name: "Hash browns" },
    { label: "🥑 Hass avocados", name: "Hass avocados" },
    { label: "🥛 Heavy whipping cream", name: "Heavy whipping cream" },
    { label: "🍿 Honey nut cereal", name: "Honey nut cereal" },
    { label: "🍏 Honeycrisp apples", name: "Honeycrisp apples" },
    { label: "🍉 Honeydew", name: "Honeydew" },
    { label: "🔥 Hot sauce", name: "Hot sauce" },
    { label: "🥑 Hummus", name: "Hummus" },
    { label: "🥬 Iceberg", name: "Iceberg" },
    { label: "🍦 Ice cream sandwiches", name: "Ice cream sandwiches" },
    { label: "☕ Instant coffee", name: "Instant coffee" },
    { label: "🥣 Instant oatmeal", name: "Instant oatmeal" },
    { label: "🌶️ Jalapeños", name: "Jalapeños" },
    { label: "🍚 Jasmine rice", name: "Jasmine rice" },
    { label: "☕ K-cups", name: "K-cups" },
    { label: "🥬 Kale", name: "Kale" },
    { label: "🥛 Kefir", name: "Kefir" },
    { label: "🍅 Ketchup", name: "Ketchup" },
    { label: "🫘 Kidney beans", name: "Kidney beans" },
    { label: "🧼 Kitchen sponges", name: "Kitchen sponges" },
    { label: "🥝 Kiwi", name: "Kiwi" },
    { label: "🧂 Kosher salt", name: "Kosher salt" },
    { label: "🥩 Lamb chops", name: "Lamb chops" },
    { label: "🥚 Large white eggs", name: "Large white eggs" },
    { label: "🍝 Lasagna sheets", name: "Lasagna sheets" },
    { label: "🧼 Laundry detergent liquid", name: "Laundry detergent liquid" },
    { label: "🧼 Laundry pods", name: "Laundry pods" },
    { label: "🧃 Lemonade", name: "Lemonade" },
    { label: "🥬 Lemons", name: "Lemons" },
    { label: "🌿 Lemongrass", name: "Lemongrass" },
    { label: "🥬 Limes", name: "Limes" },
    { label: "🥚 Liquid egg whites", name: "Liquid egg whites" },
    { label: "🧼 Liquid dish soap", name: "Liquid dish soap" },
    { label: "🧴 Liquid hand soap", name: "Liquid hand soap" },
    { label: "🦞 Lobster tails", name: "Lobster tails" },
    { label: "🐟 Mahi-mahi", name: "Mahi-mahi" },
    { label: "🍍 Mangos", name: "Mangos" },
    { label: "🥞 Maple syrup", name: "Maple syrup" },
    { label: "🧈 Margarine", name: "Margarine" },
    { label: "🥫 Marinara sauce", name: "Marinara sauce" },
    { label: "🧉 Matcha powder", name: "Matcha powder" },
    { label: "🍾 Mayonnaise", name: "Mayonnaise" },
    { label: "🧼 Microfiber cloths", name: "Microfiber cloths" },
    { label: "🥛 Milk chocolate bars", name: "Milk chocolate bars" },
    { label: "🌿 Mint", name: "Mint" },
    { label: "🌾 Molasses", name: "Molasses" },
    { label: "🧀 Monterey Jack", name: "Monterey Jack" },
    { label: "🧴 Moisturizer", name: "Moisturizer" },
    { label: "🧴 Mouthwash", name: "Mouthwash" },
    { label: "🧀 Mozzarella", name: "Mozzarella" },
    { label: "🍄 Mushroom (White Button)", name: "White button mushrooms" },
    { label: "🌶️ Nutmeg", name: "Nutmeg" },
    { label: "🍊 Navel oranges", name: "Navel oranges" },
    { label: "🍑 Nectarines", name: "Nectarines" },
    { label: "🥩 New York strip", name: "New York strip" },
    { label: "🌱 Oat milk", name: "Oat milk" },
    { label: "🧴 Oatmeal baby cereal", name: "Oatmeal baby cereal" },
    { label: "🫘 Okra", name: "Okra" },
    { label: "🫘 Sliced black olives", name: "Sliced black olives" },
    { label: "🫘 Onion powder", name: "Onion powder" },
    { label: "🧃 Orange juice", name: "Orange juice" },
    { label: "🌿 Oregano", name: "Oregano" },
    { label: "🍄 Oyster mushrooms", name: "Oyster mushrooms" },
    { label: "🥩 Pancetta", name: "Pancetta" },
    { label: "🥞 Pancake mix", name: "Pancake mix" },
    { label: "🥭 Papayas", name: "Papayas" },
    { label: "🧻 Paper bowls", name: "Paper bowls" },
    { label: "🧻 Paper napkins", name: "Paper napkins" },
    { label: "🧻 Paper plates", name: "Paper plates" },
    { label: "🧻 Paper towels", name: "Paper towels" },
    { label: "🧻 Parchment paper", name: "Parchment paper" },
    { label: "🧀 Parmesan", name: "Parmesan" },
    { label: "🫘 Parsnips", name: "Parsnips" },
    { label: "🍑 Peaches", name: "Peaches" },
    { label: "🥜 Peanuts", name: "Peanuts" },
    { label: "🍝 Penne", name: "Penne" },
    { label: "🧀 Pepper jack", name: "Pepper jack" },
    { label: "🍕 Pepperoni", name: "Pepperoni" },
    { label: "🥑 Pesto", name: "Pesto" },
    { label: "🦴 Pet waste bags", name: "Pet waste bags" },
    { label: "🍍 Pineapples", name: "Pineapples" },
    { label: "🫘 Pinto beans", name: "Pinto beans" },
    { label: "🥜 Pistachios", name: "Pistachios" },
    { label: "🍿 Pita chips", name: "Pita chips" },
    { label: "🧀 Plain Greek yogurt", name: "Plain Greek yogurt" },
    { label: "🧻 Plastic cling wrap", name: "Plastic cling wrap" },
    { label: "🧈 Plant-based butter", name: "Plant-based butter" },
    { label: "🍑 Plums", name: "Plums" },
    { label: "🍎 Pomegranates", name: "Pomegranates" },
    { label: "🍿 Popcorn", name: "Popcorn" },
    { label: "🥩 Pork ribs", name: "Pork ribs" },
    { label: "🥩 Pork chops", name: "Pork chops" },
    { label: "🥩 Pork rinds", name: "Pork rinds" },
    { label: "🥩 Pork tenderloin", name: "Pork tenderloin" },
    { label: "🍄 Portobello", name: "Portobello" },
    { label: "🥔 Potato chips", name: "Potato chips" },
    { label: "🥔 Potstickers", name: "Potstickers" },
    { label: "🌾 Powdered sugar", name: "Powdered sugar" },
    { label: "🍿 Pretzels", name: "Pretzels" },
    { label: "🍿 Protein bars", name: "Protein bars" },
    { label: "🥩 Prosciutto", name: "Prosciutto" },
    { label: "🧀 Provolone", name: "Provolone" },
    { label: "🫘 Pumpkin seeds", name: "Pumpkin seeds" },
    { label: "🧴 Q-tips", name: "Q-tips" },
    { label: "🧻 Quart ziploc bags", name: "Quart ziploc bags" },
    { label: "🥣 Quinoa", name: "Quinoa" },
    { label: "🫘 Radishes", name: "Radishes" },
    { label: "🍜 Ramen noodles", name: "Ramen noodles" },
    { label: "🍇 Raspberries", name: "Raspberries" },
    { label: "🥜 Raw almonds", name: "Raw almonds" },
    { label: "🫘 Red lentils", name: "Red lentils" },
    { label: "🫘 Red onions", name: "Red onions" },
    { label: "🍾 Relish", name: "Relish" },
    { label: "🥩 Ribeye steak", name: "Ribeye steak" },
    { label: "🧀 Ricotta", name: "Ricotta" },
    { label: "🍾 Rice vinegar", name: "Rice vinegar" },
    { label: "🍿 Rice cakes", name: "Rice cakes" },
    { label: "🍜 Rice noodles", name: "Rice noodles" },
    { label: "🍝 Rigatoni", name: "Rigatoni" },
    { label: "🍿 Ritz crackers", name: "Ritz crackers" },
    { label: "🥩 Roast beef", name: "Roast beef" },
    { label: "🥣 Rolled oats", name: "Rolled oats" },
    { label: "🥬 Romaine", name: "Romaine" },
    { label: "🍅 Roma tomatoes", name: "Roma tomatoes" },
    { label: "🌿 Rosemary", name: "Rosemary" },
    { label: "🧼 Rubber gloves", name: "Rubber gloves" },
    { label: "🥔 Russet potatoes", name: "Russet potatoes" },
    { label: "🥩 Salami", name: "Salami" },
    { label: "🥗 Salsa", name: "Salsa" },
    { label: "🍿 Saltine crackers", name: "Saltine crackers" },
    { label: "🍿 Sandwich cookies", name: "Sandwich cookies" },
    { label: "🧻 Sandwich bags", name: "Sandwich bags" },
    { label: "🧻 Sanitary pads", name: "Sanitary pads" },
    { label: "🥫 Sardines", name: "Sardines" },
    { label: "🦪 Sea scallops", name: "Sea scallops" },
    { label: "🧼 Scoring pads", name: "Scoring pads" },
    { label: "🧼 Scrub brushes", name: "Scrub brushes" },
    { label: "🌱 Seitan", name: "Seitan" },
    { label: "💧 Seltzer", name: "Seltzer" },
    { label: "🍾 Sesame oil", name: "Sesame oil" },
    { label: "🫘 Shallots", name: "Shallots" },
    { label: "🧴 Shampoo", name: "Shampoo" },
    { label: "🧴 Shaving cream", name: "Shaving cream" },
    { label: "🧴 Shaving gel", name: "Shaving gel" },
    { label: "🍄 Shiitake", name: "Shiitake" },
    { label: "🥛 Skim milk", name: "Skim milk" },
    { label: "🥩 Sliced turkey breast", name: "Sliced turkey breast" },
    { label: "🌶️ Smoked paprika", name: "Smoked paprika" },
    { label: "🥬 Sour cream", name: "Sour cream" },
    { label: "🌱 Soy milk", name: "Soy milk" },
    { label: "🐟 Soy sauce", name: "Soy sauce" },
    { label: "🍝 Spaghetti", name: "Spaghetti" },
    { label: "💧 Sparkling water", name: "Sparkling water" },
    { label: "🥬 Spinach", name: "Spinach" },
    { label: "🫘 Split peas", name: "Split peas" },
    { label: "🔥 Sriracha", name: "Sriracha" },
    { label: "🧼 Stain remover spray", name: "Stain remover spray" },
    { label: "🥩 Steel-cut oats", name: "Steel-cut oats" },
    { label: "🍓 Strawberries", name: "Strawberries" },
    { label: "🫘 Sugar snap peas", name: "Sugar snap peas" },
    { label: "🫘 Sunflower seeds", name: "Sunflower seeds" },
    { label: "🌽 Sweet corn", name: "Sweet corn" },
    { label: "🔥 Sweet chili sauce", name: "Sweet chili sauce" },
    { label: "🥔 Sweet potatoes", name: "Sweet potatoes" },
    { label: "🥬 Swiss chard", name: "Swiss chard" },
    { label: "🧀 Swiss", name: "Swiss" },
    { label: "🧻 Tall kitchen trash bags", name: "Tall kitchen trash bags" },
    { label: "🐟 Tamari", name: "Tamari" },
    { label: "🌮 Taquitos", name: "Taquitos" },
    { label: "🍟 Tater tots", name: "Tater tots" },
    { label: "🧴 Tampons", name: "Tampons" },
    { label: "🌱 Tempeh", name: "Tempeh" },
    { label: "🐟 Teriyaki sauce", name: "Teriyaki sauce" },
    { label: "🌿 Thyme", name: "Thyme" },
    { label: "🐟 Tilapia", name: "Tilapia" },
    { label: "🧻 Toilet paper", name: "Toilet paper" },
    { label: "🧼 Toilet bowl cleaner", name: "Toilet bowl cleaner" },
    { label: "🥫 Tomato juice", name: "Tomato juice" },
    { label: "🥫 Tomato paste", name: "Tomato paste" },
    { label: "🥫 Tomato sauce", name: "Tomato sauce" },
    { label: "🥫 Tomato soup", name: "Tomato soup" },
    { label: "🍿 Tortilla chips", name: "Tortilla chips" },
    { label: "🫓 Tortilla", name: "Tortilla" },
    { label: "🧴 Toothbrushes", name: "Toothbrushes" },
    { label: "🐟 Trout", name: "Trout" },
    { label: "🐟 Tuna steaks", name: "Tuna steaks" },
    { label: "🫘 Turnips", name: "Turnips" },
    { label: "🫘 Turmeric", name: "Turmeric" },
    { label: "🥛 Unsalted butter", name: "Unsalted butter" },
    { label: "🍦 Vanilla ice cream", name: "Vanilla ice cream" },
    { label: "🌾 Vanilla extract", name: "Vanilla extract" },
    { label: "🥛 Vanilla yogurt", name: "Vanilla yogurt" },
    { label: "🥣 Vegetable broth", name: "Vegetable broth" },
    { label: "🍾 Vegetable oil", name: "Vegetable oil" },
    { label: "🥜 Walnuts", name: "Walnuts" },
    { label: "🍉 Watercress", name: "Watercress" },
    { label: "🍉 Watermelon", name: "Watermelon" },
    { label: "🧻 Wax paper", name: "Wax paper" },
    { label: "🐾 Wet cat food", name: "Wet cat food" },
    { label: "🐾 Wet dog food", name: "Wet dog food" },
    { label: "🍿 Wheat crackers", name: "Wheat crackers" },
    { label: "🍾 White cleaning vinegar", name: "White cleaning vinegar" },
    { label: "🦪 White shrimp", name: "White shrimp" },
    { label: "🍾 White vinegar", name: "White vinegar" },
    { label: "Whole chicken", name: "Whole chicken" },
    { label: "🥛 Whole milk", name: "Whole milk" },
    { label: "🌾 Whole wheat flour", name: "Whole wheat flour" },
    { label: "🧼 Wood polish", name: "Wood polish" },
    { label: "🐟 Worcestershire sauce", name: "Worcestershire sauce" },
    { label: "🫘 Yellow onions", name: "Yellow onions" },
    { label: "🫘 Yellow squash", name: "Yellow squash" },
    { label: "🍾 Yellow mustard", name: "Yellow mustard" },
    { label: "🌾 Yeast", name: "Yeast" },
    { label: "🥒 Zucchini", name: "Zucchini" }
  ];
  
  // 2. BACKBONE CATEGORY STRUCUTURAL GROUPS
  export const GROCERY_CATALOG = {
    fruits: { keywords: ['apple', 'banana', 'berr', 'strawberry', 'blueberry', 'raspberry', 'citrus', 'lemon', 'lime', 'orange', 'melon', 'watermelon', 'avocado', 'grape', 'peach', 'cherry', 'kiwi', 'mango'], cat: 'Fresh Produce', sub: 'Fruits' },
    vegetables: { keywords: ['green', 'lettuce', 'spinach', 'potato', 'carrot', 'broccoli', 'tomato', 'onion', 'garlic', 'cucumber', 'pepper', 'corn', 'mushroom', 'cabbage', 'zucchini', 'eggplant'], cat: 'Fresh Produce', sub: 'Vegetables' },
    poultry: { keywords: ['chicken', 'turkey', 'wing', 'drumstick', 'breast'], cat: '🥩 Meat, Seafood & Deli', sub: 'Meat & Poultry' },
    redmeat: { keywords: ['beef', 'pork', 'lamb', 'steak', 'mince', 'rib', 'chop', 'meat', 'burger'], cat: '🥩 Meat, Seafood & Deli', sub: 'Meat & Poultry' },
    seafood: { keywords: ['salmon', 'shrimp', 'cod', 'tuna', 'fish', 'prawn', 'crab', 'lobster'], cat: '🥩 Meat, Seafood & Deli', sub: 'Fish & Seafood' },
    deli: { keywords: ['salami', 'ham', 'bacon', 'sausage', 'pepperoni', 'pastrami', 'olive'], cat: '🥩 Meat, Seafood & Deli', sub: 'Deli' },
    dairyBase: { keywords: ['milk', 'butter', 'cream', 'sour cream', 'yogurt', 'ayran', 'cacik'], cat: '🧀 Dairy & Refrigerated', sub: 'Dairy' },
    eggsItem: { keywords: ['egg'], cat: '🧀 Dairy & Refrigerated', sub: 'Dairy' },
    cheeseItem: { keywords: ['cheese', 'cheddar', 'mozzarella', 'feta', 'kasar', 'peynir'], cat: '🧀 Dairy & Refrigerated', sub: 'Cheese' },
    veganDairy: { keywords: ['almond milk', 'oat milk', 'soy milk', 'vegan cheese'], cat: '🧀 Dairy & Refrigerated', sub: 'Plant-Based Alternatives' },
    grains: { keywords: ['rice', 'oat', 'quinoa', 'bread', 'tortilla', 'flour', 'baking', 'yeast', 'sugar', 'powder'], cat: '🥫 Center Store (Pantry Staples)', sub: 'Grains & Baking' },
    pasta: { keywords: ['pasta', 'spaghetti', 'macaroni', 'noodle'], cat: '🥫 Center Store (Pantry Staples)', sub: 'Grains & Pasta' },
    canned: { keywords: ['soup', 'bean', 'sauce', 'paste', 'canned'], cat: '🥫 Center Store (Pantry Staples)', sub: 'Canned Goods' },
    condiments: { keywords: ['oil', 'olive oil', 'vinegar', 'mayo', 'ketchup', 'mustard', 'sauce', 'salt', 'pepper', 'spice'], cat: '🥫 Center Store (Pantry Staples)', sub: 'Condiments & Spices' },
    snacks: { keywords: ['chip', 'nut', 'popcorn', 'cracker', 'cookie', 'chocolate', 'biscuit', 'sweet', 'candy'], cat: '🥫 Center Store (Pantry Staples)', sub: 'Snacks' },
    frozenMeals: { keywords: ['pizza', 'burrito', 'nugget', 'frozen meal', 'waffle'], cat: '🧊 Frozen Foods', sub: 'Frozen Meals' },
    frozenProduce: { keywords: ['frozen vegetable', 'frozen fruit', 'frozen berry', 'peas'], cat: '🧊 Frozen Foods', sub: 'Frozen Produce' },
    frozenTreats: { keywords: ['ice cream', 'popsicle', 'sorbet'], cat: '🧊 Frozen Foods', sub: 'Frozen Treats' },
    hotDrinks: { keywords: ['coffee', 'bean', 'tea', 'cai', 'espresso', 'hot chocolate'], cat: '☕ Beverages', sub: 'Hot Drinks' },
    coldDrinks: { keywords: ['water', 'juice', 'soda', 'cola', 'sprite', 'fanta', 'sports drink', 'energy drink'], cat: '☕ Beverages', sub: 'Cold Drinks' },
    alcohol: { keywords: ['beer', 'wine', 'spirit', 'vodka', 'whiskey', 'raki'], cat: '☕ Beverages', sub: 'Alcohol' },
    paper: { keywords: ['toilet paper', 'paper towel', 'napkin', 'tissue'], cat: '🧻 Non-Food & Household', sub: 'Paper Products' },
    cleaning: { keywords: ['soap', 'detergent', 'spray', 'cleaner', 'bleach', 'sponge'], cat: '🧻 Non-Food & Household', sub: 'Cleaning Supplies' },
    personal: { keywords: ['shampoo', 'toothpaste', 'deodorant', 'bandage', 'medicine', 'vitamin', 'brush'], cat: '🧻 Non-Food & Household', sub: 'Personal & Health Care' },
    pet: { keywords: ['cat food', 'dog food', 'pet', 'treats'], cat: '🧻 Non-Food & Household', sub: 'Pet Supplies' }
  };