// ============================================================================
// 1. UNIQUE ITEM EMOJI REGISTRY (Supports cross-language lowercase keyword lookups)
// ============================================================================
export const ITEM_EMOJIS = {
  // --- FRUITS ---
  'apple': '🍎', 'elma': '🍎',
  'banana': '🍌', 'muz': '🍌',
  'strawberry': '🍓', 'çilek': '🍓',
  'blueberry': '🫐', 'yaban mersini': '🫐',
  'cherry': '🍒', 'kiraz': '🍒', 'vişne': '🍒',
  'lemon': '🍋', 'limon': '🍋',
  'lime': '🍋',
  'orange': '🍊', 'portakal': '🍊',
  'citrus': '🍊', 'narenciye': '🍊',
  'melon': '🍈', 'kavun': '🍈',
  'watermelon': '🍉', 'karpuz': '🍉',
  'avocado': '🥑', 'avakado': '🥑', 'avokado': '🥑',
  'grape': '🍇', 'üzüm': '🍇',
  'peach': '🍑', 'şeftali': '🍑',
  'kiwi': '🥝', 'kivi': '🥝',
  'mango': '🥭',

  // --- VEGETABLES ---
  'potato': '🥔', 'patates': '🥔',
  'carrot': '🥕', 'havuç': '🥕',
  'broccoli': '🥦', 'brokoli': '🥦',
  'tomato': '🍅', 'domates': '🍅',
  'onion': '🧅', 'soğan': '🧅',
  'garlic': '🧄', 'sarımsak': '🧄',
  'cucumber': '🥒', 'salatalık': '🥒', 'hıyar': '🥒',
  'bell pepper': '🫑', 'biber': '🫑', 'dolmalık biber': '🫑',
  'corn': '🌽', 'mısır': '🌽',
  'mushroom': '🍄', 'mantar': '🍄',
  'cabbage': '🥬', 'lahana': '🥬',
  'lettuce': '🥬', 'marul': '🥬',
  'spinach': '🥬', 'ispanak': '🥬',
  'zucchini': '🥒', 'kabak': '🥒',
  'eggplant': '🍆', 'patlıcan': '🍆',

  // --- MEAT & SEAFOOD ---
  'chicken': '🍗', 'tavuk': '🍗',
  'turkey': '🦃', 'hindi': '🦃',
  'wing': '🍗', 'kanat': '🍗',
  'drumstick': '🍗', 'baget': '🍗',
  'breast': '🥩', 'göğüs': '🥩',
  'beef': '🥩', 'dana': '🥩', 'sığır': '🥩',
  'steak': '🥩', 'biftek': '🥩', 'antrikot': '🥩',
  'mince': '🥩', 'kıyma': '🥩',
  'burger': '🍔', 'köfte': '🍔',
  'lamb': '🥩', 'kuzu': '🥩',
  'pork': '🥓',
  'bacon': '🥓', 'domuz pastırması': '🥓',
  'sausage': '🌭', 'sosis': '🌭',
  'pepperoni': '🍕',
  'salami': '🥓', 'sucuk': '🥓', 'salam': '🥓',
  'ham': '🍖',
  'salmon': '🐟', 'somon': '🐟',
  'fish': '🐟', 'balık': '🐟',
  'tuna': '🐟', 'ton balığı': '🐟',
  'shrimp': '🍤', 'karides': '🍤',
  'prawn': '🍤',
  'crab': '🦀', 'yengeç': '🦀',
  'lobster': '🦞', 'istakoz': '🦞',

  // --- DAIRY & REFRIGERATED ---
  'milk': '🥛', 'süt': '🥛',
  'butter': '🧈', 'tereyağı': '🧈',
  'cream': '🥛', 'krema': '🥛', 'kaymak': '🥛',
  'sour cream': '🥬', 'ekşi krema': '🥬',
  'yogurt': '🥛', 'yoğurt': '🥛',
  'ayran': '🥛',
  'cacik': '🥣', 'cacık': '🥣',
  'egg': '🥚', 'yumurta': '🥚',
  'cheese': '🧀', 'peynir': '🧀',
  'cheddar': '🧀',
  'mozzarella': '🧀',
  'feta': '🧀', 'beyaz peynir': '🧀',
  'kasar': '🧀', 'kaşar': '🧀', 'kaşar peyniri': '🧀',
  'almond milk': '🌱', 'badem sütü': '🌱',
  'oat milk': '🌱', 'yulaf sütü': '🌱',
  'soy milk': '🌱', 'soya sütü': '🌱',

  // --- PANTRY STAPLES ---
  'rice': '🍚', 'pirinç': '🍚',
  'oat': '🥣', 'yulaf': '🥣',
  'quinoa': '🥣', 'kinoa': '🥣',
  'bread': '🍞', 'ekmek': '🍞',
  'tortilla': '🫓', 'lavaş': '🫓',
  'flour': '🌾', 'un': '🌾',
  'sugar': '🍬', 'şeker': '🍬',
  'pasta': '🍝', 'makarna': '🍝',
  'spaghetti': '🍝', 'spagetti': '🍝',
  'macaroni': '🍝',
  'noodle': '🍜', 'nrişte': '🍜',
  'soup': '🥣', 'çorba': '🥣',
  'bean': '🫘', 'fasulye': '🫘', 'bakliyat': '🫘',
  'sauce': '🥫', 'sos': '🥫',
  'paste': '🥫', 'salça': '🥫',
  'canned': '🥫', 'konserve': '🥫',
  'oil': '🍾', 'yağ': '🍾',
  'olive oil': '🫒', 'zeytinyağı': '🫒',
  'vinegar': '🍾', 'sirke': '🍾',
  'mayo': '🍾', 'mayonez': '🍾',
  'ketchup': '🍅', 'ketçap': '🍅',
  'mustard': '🍾', 'hardal': '🍾',
  'salt': '🧂', 'tuz': '🧂',
  'black pepper': '🧂', 'karabiber': '🧂',
  'spice': '🌶️', 'baharat': '🌶️',

  // --- SNACKS & TREATS ---
  'chip': '🥔', 'cips': '🥔',
  'nut': '🥜', 'kuruyemiş': '🥜', 'çerez': '🥜',
  'popcorn': '🍿', 'patlamış mısır': '🍿',
  'cracker': '🫓', 'kraker': '🫓',
  'cookie': '🍪', 'kurabiye': '🍪',
  'chocolate': '🍫', 'çikolata': '🍫',
  'biscuit': '🍪', 'bisküvi': '🍪',
  'sweet': '🍬', 'tatlı': '🍬',
  'candy': '🍬', 'şekerleme': '🍬',
  'ice cream': '🍦', 'dondurma': '🍦',
  'popsicle': '🍧', 'meyveli buz': '🍧',

  // --- BEVERAGES ---
  'coffee': '☕', 'kahve': '☕',
  'coffee bean': '🫘', 'kahve çekirdeği': '🫘',
  'tea': '🍵', 'çay': '🍵',
  'cai': '🍵',
  'espresso': '☕',
  'hot chocolate': '☕', 'sıcak çikolata': '☕',
  'water': '💧', 'su': '💧',
  'juice': '🧃', 'meyve suyu': '🧃',
  'soda': '🥤', 'gazoz': '🥤', 'maden suyu': '🥤',
  'cola': '🥤', 'kola': '🥤',
  'sprite': '🥤',
  'fanta': '🥤',
  'beer': '🍺', 'bira': '🍺',
  'wine': '🍷', 'şarap': '🍷',
  'vodka': '🍾', 'votka': '🍾',
  'whiskey': '🥃', 'viski': '🥃',
  'raki': '🥛', 'rakı': '🥛',

  // --- HOUSEHOLD & PET ---
  'toilet paper': '🧻', 'tuvalet kağıdı': '🧻',
  'paper towel': '🧻', 'kağıt havlu': '🧻',
  'napkin': '🧻', 'peçete': '🧻',
  'tissue': '🧻', 'mendil': '🧻',
  'soap': '🧼', 'sabun': '🧼',
  'detergent': '🧼', 'deterjan': '🧼',
  'spray': '🧴', 'sprey': '🧴',
  'cleaner': '🧼', 'temizleyici': '🧼',
  'bleach': '🧴', 'çamaşır suyu': '🧴',
  'sponge': '🧽', 'sünger': '🧽',
  'shampoo': '🧴', 'şampuan': '🧴',
  'toothpaste': '🪥', 'diş macunu': '🪥',
  'deodorant': '🧴',
  'bandage': '🩹', 'yara bandı': '🩹',
  'medicine': '💊', 'ilaç': '💊',
  'vitamin': '💊',
  'cat food': '🐱', 'kedi maması': '🐱',
  'dog food': '🐶', 'köpek maması': '🐶',
  'pet': '🐾', 'evcil hayvan': '🐾',
  'treats': '🦴', 'ödül maması': '🦴'
};

// ============================================================================
// 2. PREDEFINED ITEMS (Bilingual objects containing language variants maps)
// ============================================================================
export const PREDEFINED_ITEMS = [
  { label: { en: "🥛 2% Milk", tr: "🥛 %2 Yağlı Süt" }, name: { en: "2% Milk", tr: "2% Yağlı Süt" } },
  { label: { en: "🧃 Apple juice", tr: "🧃 Elma Suyu" }, name: { en: "Apple juice", tr: "Elma Suyu" } },
  { label: { en: "🌾 All-purpose flour", tr: "🌾 Çok Amaçlı Un" }, name: { en: "All-purpose flour", tr: "Çok Amaçlı Un" } },
  { label: { en: "🌱 Almond butter", tr: "🌱 Badem Ezmesi" }, name: { en: "Almond butter", tr: "Badem Ezmesi" } },
  { label: { en: "🌾 Almond flour", tr: "🌾 Badem Unu" }, name: { en: "Almond flour", tr: "Badem Unu" } },
  { label: { en: "🌱 Almond milk", tr: "🌱 Badem Sütü" }, name: { en: "Almond milk", tr: "Badem Sütü" } },
  { label: { en: "🧴 Aluminum foil", tr: "🧴 Alüminyum Folyo" }, name: { en: "Aluminum foil", tr: "Alüminyum Folyo" } },
  { label: { en: "🧴 All-purpose cleaner spray", tr: "🧴 Çok Amaçlı Temizleyici Sprey" }, name: { en: "All-purpose cleaner spray", tr: "Çok Amaçlı Temizleyici Sprey" } },
  { label: { en: "🥫 Anchovies", tr: "🥫 Ançüez" }, name: { en: "Anchovies", tr: "Ançüez" } },
  { label: { en: "🧴 Antiperspirant", tr: "🧴 Antiprespirant Deodorant" }, name: { en: "Antiperspirant", tr: "Antiperspirant" } },
  { label: { en: "🍚 Arborio rice", tr: "🍚 Arborio Pirinci (Rizotto)" }, name: { en: "Arborio rice", tr: "Arborio Pirinci" } },
  { label: { en: "🥬 Arugula", tr: "🥬 Roka" }, name: { en: "Arugula", tr: "Roka" } },
  { label: { en: "🐟 Atlantic salmon", tr: "🐟 Atlas Okyanusu Somonu" }, name: { en: "Atlantic salmon", tr: "Atlas Okyanusu Somonu" } },
  { label: { en: "🥑 Avocado oil", tr: "🥑 Avokado Yağı" }, name: { en: "Avocado oil", tr: "Avokado Yağı" } },
  { label: { en: "🧴 Baby formula", tr: "🧴 Bebek Maması (Toz Formül)" }, name: { en: "Baby formula", tr: "Bebek Maması" } },
  { label: { en: "🥫 Baby food jars", tr: "🥫 Kavanoz Bebek Maması" }, name: { en: "Baby food jars", tr: "Kavanoz Bebek Maması" } },
  { label: { en: "🧴 Baby lotion", tr: "🧴 Bebek Losyonu" }, name: { en: "Baby lotion", tr: "Bebek Losyonu" } },
  { label: { en: "🧴 Baby shampoo", tr: "🧴 Bebek Şampuanı" }, name: { en: "Baby shampoo", tr: "Bebek Şampuanı" } },
  { label: { en: "🧴 Baby wipes", tr: "🧴 Islak Bebek Mendili" }, name: { en: "Baby wipes", tr: "Islak Bebek Mendili" } },
  { label: { en: "🥓 Bacon", tr: "🥓 Dana Füme / Bacon" }, name: { en: "Bacon", tr: "Bacon" } },
  { label: { en: "🥫 Baked beans", tr: "🥫 Fırınlanmış Fasulye Konservesi" }, name: { en: "Baked beans", tr: "Fırınlanmış Fasulye" } },
  { label: { en: "🌾 Baking powder", tr: "🌾 Hamur Kabartma Tozu" }, name: { en: "Baking powder", tr: "Hamur Kabartma Tozu" } },
  { label: { en: "🌾 Baking soda", tr: "🌾 Karbonat" }, name: { en: "Baking soda", tr: "Karbonat" } },
  { label: { en: "🍾 Balsamic vinegar", tr: "🍾 Balzamik Sirke" }, name: { en: "Balsamic vinegar", tr: "Balzamik Sirke" } },
  { label: { en: "🍌 Bananas", tr: "🍌 Muz" }, name: { en: "Bananas", tr: "Muz" } },
  { label: { en: "🧴 Bar soap", tr: "🧴 Katı Sabun" }, name: { en: "Bar soap", tr: "Katı Sabun" } },
  { label: { en: "🔥 Barbecue sauce", tr: "🔥 Barbekü Sosu" }, name: { en: "Barbecue sauce", tr: "Barbekü Sosu" } },
  { label: { en: "🥣 Barley", tr: "🥣 Arpa" }, name: { en: "Barley", tr: "Arpa" } },
  { label: { en: "🍐 Bartlett pears", tr: "🍐 Armut" }, name: { en: "Bartlett pears", tr: "Armut" } },
  { label: { en: "🍚 Basmati rice", tr: "🍚 Basmati Pirinç" }, name: { en: "Basmati rice", tr: "Basmati Pirinç" } },
  { label: { en: "🌿 Basil", tr: "🌿 Fesleğen" }, name: { en: "Basil", tr: "Fesleğen" } },
  { label: { en: "🫘 Black beans", tr: "🫘 Siyah Fasulye" }, name: { en: "Black beans", tr: "Siyah Fasulye" } },
  { label: { en: "🥩 Beef chuck roast", tr: "🥩 Dana Gerdan / Rosto" }, name: { en: "Beef chuck roast", tr: "Dana Gerdan" } },
  { label: { en: "🥣 Beef broth", tr: "🥣 Et Suyu" }, name: { en: "Beef broth", tr: "Et Suyu" } },
  { label: { en: "🥩 Beef stew meat", tr: "🥩 Sote Et / Kuşbaşı" }, name: { en: "Beef stew meat", tr: "Kuşbaşı Et" } },
  { label: { en: "🫘 Beets", tr: "🫘 Pancar" }, name: { en: "Beets", tr: "Pancar" } },
  { label: { en: "🍺 Beer", tr: "🍺 Bira" }, name: { en: "Beer", tr: "Bira" } },
  { label: { en: "🫑 Bell peppers", tr: "🫑 Dolmalık Biberler" }, name: { en: "Bell peppers", tr: "Dolmalık Biber" } },
  { label: { en: "🍪 Biscuit", tr: "🍪 Bisküvi" }, name: { en: "Biscuit", tr: "Bisküvi" } },
  { label: { en: "🍪 Brownies", tr: "🍪 Brownie" }, name: { en: "Brownies", tr: "Brownie" } },
  { label: { en: "🍇 Blackberries", tr: "🍇 Böğürtlen" }, name: { en: "Blackberries", tr: "Böğürtlen" } },
  { label: { en: "🧂 Black peppercorns", tr: "🧂 Tane Karabiber" }, name: { en: "Black peppercorns", tr: "Tane Karabiber" } },
  { label: { en: "🍵 Black tea bags", tr: "🍵 Poşet Siyah Çay" }, name: { en: "Black tea bags", tr: "Poşet Siyah Çay" } },
  { label: { en: "🍊 Blood oranges", tr: "🍊 Kan Portakalı" }, name: { en: "Blood oranges", tr: "Kan Portakalı" } },
  { label: { en: "🫐 Blueberries", tr: "🫐 Yaban Mersini" }, name: { en: "Blueberries", tr: "Yaban Mersini" } },
  { label: { en: "🧀 Blue cheese", tr: "🧀 Rokfor / Küflü Peynir" }, name: { en: "Blue cheese", tr: "Küflü Peynir" } },
  { label: { en: "🦪 Blue mussels", tr: "🦪 Midye" }, name: { en: "Blue mussels", tr: "Midye" } },
  { label: { en: "🥦 Bok choy", tr: "🥦 Çin Lahanası / Bok Choy" }, name: { en: "Bok choy", tr: "Bok Choy" } },
  { label: { en: "🥩 Bologna", tr: "🥩 Bolon Sosisi / Salam" }, name: { en: "Bologna", tr: "Salam" } },
  { label: { en: "🧴 Body lotion", tr: "🧴 Vücut Losyonu" }, name: { en: "Body lotion", tr: "Vücut Losyonu" } },
  { label: { en: "🧴 Body wash", tr: "🧴 Duş Jeli" }, name: { en: "Body wash", tr: "Duş Jeli" } },
  { label: { en: "💧 Bottled spring water", tr: "💧 Şişe Kaynak Suyu" }, name: { en: "Bottled spring water", tr: "Şişe Su" } },
  { label: { en: "🧀 Brie", tr: "🧀 Brie Peyniri" }, name: { en: "Brie", tr: "Brie Peyniri" } },
  { label: { en: "🥦 Broccoli", tr: "🥦 Brokoli" }, name: { en: "Broccoli", tr: "Brokoli" } },
  { label: { en: "🥦 Broccolini", tr: "🥦 Taze Küçük Brokoli" }, name: { en: "Broccolini", tr: "Küçük Brokoli" } },
  { label: { en: "🍚 Brown rice", tr: "🍚 Esmer Pirinç" }, name: { en: "Brown rice", tr: "Esmer Pirinç" } },
  { label: { en: "🌾 Brown sugar", tr: "🌾 Esmer Şeker" }, name: { en: "Brown sugar", tr: "Esmer Şeker" } },
  { label: { en: "🥦 Brussels sprouts", tr: "🥦 Brüksel Lahanası" }, name: { en: "Brussels sprouts", tr: "Brüksel Lahanası" } },
  { label: { en: "🛁 Bubble bath", tr: "🛁 Banyo Köpüğü" }, name: { en: "Bubble bath", tr: "Banyo Köpüğü" } },
  { label: { en: "🥛 Buttermilk", tr: "🥛 Yayık Sütü" }, name: { en: "Buttermilk", tr: "Yayık Sütü" } },
  { label: { en: "🥬 Cabbage", tr: "🥬 Beyaz Lahana" }, name: { en: "Cabbage", tr: "Lahana" } },
  { label: { en: "🥫 Canned albacore tuna", tr: "🥫 Ton Balığı Konservesi" }, name: { en: "Canned albacore tuna", tr: "Ton Balığı Konservesi" } },
  { label: { en: "🥫 Canned chicken breast", tr: "🥫 Konserve Tavuk Göğsü" }, name: { en: "Canned chicken breast", tr: "Konserve Tavuk Göğsü" } },
  { label: { en: "🥫 Canned salmon", tr: "🥫 Somon Konservesi" }, name: { en: "Canned salmon", tr: "Somon Konservesi" } },
  { label: { en: "🍉 Cantaloupe", tr: "🍉 Kavun" }, name: { en: "Cantaloupe", tr: "Kavun" } },
  { label: { en: "🫘 Carrots", tr: "🫘 Havuç" }, name: { en: "Carrots", tr: "Havuç" } },
  { label: { en: "🌱 Cashew milk", tr: "🌱 Kaju Sütü" }, name: { en: "Cashew milk", tr: "Kaju Sütü" } },
  { label: { en: "🥜 Cashews", tr: "🥜 Kaju" }, name: { en: "Cashews", tr: "Kaju" } },
  { label: { en: "🐱 Cat food", tr: "🐱 Kedi Maması" }, name: { en: "Cat food", tr: "Kedi Maması" } },
  { label: { en: "🐾 Cat litter", tr: "🐾 Kedi Kumu" }, name: { en: "Cat litter", tr: "Kedi Kumu" } },
  { label: { en: "🦴 Cat treats", tr: "🦴 Kedi Ödül Maması" }, name: { en: "Cat treats", tr: "Kedi Ödülü" } },
  { label: { en: "🥦 Cauliflower", tr: "🥦 Karnabahar" }, name: { en: "Cauliflower", tr: "Karnabahar" } },
  { label: { en: "🌶️ Cayenne pepper", tr: "🌶️ Acı Kırmızı Toz Biber" }, name: { en: "Cayenne pepper", tr: "Arnavut Biberi" } },
  { label: { en: "🥬 Celery", tr: "🥬 Kereviz Sapı" }, name: { en: "Celery", tr: "Kereviz Sapı" } },
  { label: { en: "🍵 Chamomile tea", tr: "🍵 Papatya Çayı" }, name: { en: "Chamomile tea", tr: "Papatya Çayı" } },
  { label: { en: "🧀 Sharp cheddar", tr: "🧀 Eski Çedar Peyniri" }, name: { en: "Sharp cheddar", tr: "Çedar Peyniri" } },
  { label: { en: "🍒 Cherries", tr: "🍒 Kiraz" }, name: { en: "Cherries", tr: "Kiraz" } },
  { label: { en: "🍅 Cherry tomatoes", tr: "🍅 Çeri Domatesi" }, name: { en: "Cherry tomatoes", tr: "Çeri Domates" } },
  { label: { en: "🫘 Chia seeds", tr: "🫘 Çiya Tohumu" }, name: { en: "Chia seeds", tr: "Çiya Tohumu" } },
  { label: { en: "🍗 Chicken breasts", tr: "🍗 Tavuk Göğsü" }, name: { en: "Chicken breasts", tr: "Tavuk Göğsü" } },
  { label: { en: "🥣 Chicken broth", tr: "🥣 Tavuk Suyu" }, name: { en: "Chicken broth", tr: "Tavuk Suyu" } },
  { label: { en: "🥫 Chicken noodle soup", tr: "🥫 Tavuklu Şehriye Çorbası" }, name: { en: "Chicken noodle soup", tr: "Tavuklu Şehriye Çorbası" } },
  { label: { en: "🍗 Chicken nuggets", tr: "🍗 Tavuk Nugget" }, name: { en: "Chicken nuggets", tr: "Tavuk Nugget" } },
  { label: { en: "🍗 Chicken thighs", tr: "🍗 Tavuk But / Pirzola" }, name: { en: "Chicken thighs", tr: "Tavuk But" } },
  { label: { e: "🍗 Chicken wings", tr: "🍗 Tavuk Kanat" }, name: { en: "Chicken wings", tr: "Tavuk Kanat" } },
  { label: { en: "🌶️ Chili powder", tr: "🌶️ Acı Toz Biber" }, name: { en: "Chili powder", tr: "Chili Toz Biber" } },
  { label: { en: "🍫 Chocolate chip cookies", tr: "🍫 Damla Çikolatalı Kurabiye" }, name: { en: "Chocolate chip cookies", tr: "Çikolatalı Kurabiye" } },
  { label: { en: "🍫 Chocolate chips", tr: "🍫 Damla Çikolata" }, name: { en: "Chocolate chips", tr: "Damla Çikolata" } },
  { label: { en: "🍦 Chocolate ice cream", tr: "🍦 Çikolatalı Dondurma" }, name: { en: "Chocolate ice cream", tr: "Çikolatalı Dondurma" } },
  { label: { en: "🌿 Cilantro", tr: "🌿 Kişniş (Taze)" }, name: { en: "Cilantro", tr: "Taze Kişniş" } },
  { label: { en: "🌿 Chives", tr: "🌿 Frenk Soğanı" }, name: { en: "Chives", tr: "Frenk Soğanı" } },
  { label: { en: "🦪 Clams", tr: "🦪 Kum Midyesi" }, name: { en: "Clams", tr: "Kum Midyesi" } },
  { label: { en: "🍊 Clementines", tr: "🍊 Mandalina" }, name: { en: "Clementines", tr: "Mandalina" } },
  { label: { en: "🌾 Cocoa powder", tr: "🌾 Kakao Tozu" }, name: { en: "Cocoa powder", tr: "Kakao Tozu" } },
  { label: { en: "🥥 Coconut milk", tr: "🥥 Hindistan Cevizi Sütü" }, name: { en: "Coconut milk", tr: "Hindistan Cevizi Sütü" } },
  { label: { en: "🥥 Coconut oil", tr: "🥥 Hindistan Cevizi Yağı" }, name: { en: "Coconut oil", tr: "Hindistan Cevizi Yağı" } },
  { label: { en: "🥥 Coconuts", tr: "🥥 Hindistan Cevizi" }, name: { en: "Coconuts", tr: "Hindistan Cevizi" } },
  { label: { en: "🐟 Cod fillets", tr: "🐟 Morina Balığı Filetosu" }, name: { en: "Cod fillets", tr: "Morina Fileto" } },
  { label: { en: "☕ Coffee beans", tr: "☕ Kahve Çekirdeği" }, name: { en: "Coffee beans", tr: "Kahve Çekirdeği" } },
  { label: { en: "🥬 Collard greens", tr: "🥬 Kara Lahana" }, name: { en: "Collard greens", tr: "Kara Lahana" } },
  { label: { en: "🥛 Condensed milk", tr: "🥛 Yoğunlaştırılmış Şekerli Süt" }, name: { en: "Condensed milk", tr: "Yoğunlaştırılmış Süt" } },
  { label: { en: "🧴 Conditioner", tr: "🧴 Saç Kremi" }, name: { en: "Conditioner", tr: "Saç Kremi" } },
  { label: { en: "🍪 Cookie dough", tr: "🍪 Kurabiye Hamuru" }, name: { en: "Cookie dough", tr: "Kurabiye Hamuru" } },
  { label: { en: "🍿 Corn chips", tr: "🍿 Mısır Cipsi" }, name: { en: "Corn chips", tr: "Mısır Cipsi" } },
  { label: { en: "🍿 Cornflakes", tr: "🍿 Mısır Gevreği" }, name: { en: "Cornflakes", tr: "Mısır Gevreği" } },
  { label: { en: "🌾 Cornstarch", tr: "🌾 Mısır Nişastası" }, name: { en: "Cornstarch", tr: "Mısır Nişastası" } },
  { label: { en: "🧴 Cotton pads", tr: "🧴 Makyaj Temizleme Pamuğu" }, name: { en: "Cotton pads", tr: "Makyaj Pamuğu" } },
  { label: { en: "🧀 Cottage cheese", tr: "🧀 Lor Peyniri" }, name: { en: "Cottage cheese", tr: "Lor Peyniri" } },
  { label: { en: "🥣 Couscous", tr: "🥣 Kuskus" }, name: { en: "Couscous", tr: "Kuskus" } },
  { label: { en: "🦪 Crab meat", tr: "🦪 Yengeç Eti" }, name: { en: "Crab meat", tr: "Yengeç Eti" } },
  { label: { en: "🧃 Cranberry juice", tr: "🧃 Turna Yemişi Suyu" }, name: { en: "Cranberry juice", tr: "Turna Yemişi Suyu" } },
  { label: { en: "🧀 Cream cheese", tr: "🧀 Taze Krem Peynir" }, name: { en: "Cream cheese", tr: "Krem Peynir" } },
  { label: { en: "🌱 Creamy peanut butter", tr: "🌱 Pürüzsüz Fıstık Ezmesi" }, name: { en: "Creamy peanut butter", tr: "Fıstık Ezmesi" } },
  { label: { en: "🥛 Crème fraîche", tr: "🥛 Taze Ekşi Krema (Fraiche)" }, name: { en: "Crème fraîche", tr: "Creme Fraiche" } },
  { label: { en: "🍿 Crunchy peanut butter", tr: "🍿 Parçacıklı Fıstık Ezmesi" }, name: { en: "Crunchy peanut butter", tr: "Parçacıklı Fıstık Ezmesi" } },
  { label: { en: "🥫 Crushed tomatoes", tr: "🥫 Ezilmiş Domates Konservesi" }, name: { en: "Crushed tomatoes", tr: "Ezilmiş Domates" } },
  { label: { en: "🌶️ Crushed red pepper flakes", tr: "🌶️ Pul Biber" }, name: { en: "Crushed red pepper flakes", tr: "Pul Biber" } },
  { label: { en: "🥒 Cucumber", tr: "🥒 Salatalık" }, name: { en: "Cucumber", tr: "Salatalık" } },
  { label: { en: "🌶️ Curry powder", tr: "🌶️ Köri Tozu" }, name: { en: "Curry powder", tr: "Köri Tozu" } },
  { label: { en: "🍫 Dark chocolate", tr: "🍫 Bitter Çikolata" }, name: { en: "Dark chocolate", tr: "Bitter Çikolata" } },
  { label: { en: "🥩 Deli ham", tr: "🥩 Şarküteri Jambon" }, name: { en: "Deli ham", tr: "Jambon" } },
  { label: { en: "🧴 Dental floss", tr: "🧴 Diş İpi" }, name: { en: "Dental floss", tr: "Diş İpi" } },
  { label: { en: "🧴 Deodorant", tr: "🧴 Deodorant" }, name: { en: "Deodorant", tr: "Deodorant" } },
  { label: { en: "🥫 Diced tomatoes", tr: "🥫 Küp Kesilmiş Domates Konservesi" }, name: { en: "Diced tomatoes", tr: "Küp Domates" } },
  { label: { en: "🥤 Diet soda", tr: "🥤 Diyet Gazlı İçecek / Cola" }, name: { en: "Diet soda", tr: "Diyet Kola" } },
  { label: { en: "🧴 Diapers", tr: "🧴 Bebek Bezi" }, name: { en: "Diapers", tr: "Bebek Bezi" } },
  { label: { en: "🍾 Dijon mustard", tr: "🍾 Dijon Hardalı" }, name: { en: "Dijon mustard", tr: "Dijon Hardalı" } },
  { label: { en: "🌿 Dill", tr: "🌿 Dereotu" }, name: { en: "Dill", tr: "Dereotu" } },
  { label: { en: "🧼 Disinfecting wipes", tr: "🧼 Dezenfektan Mendil" }, name: { en: "Disinfecting wipes", tr: "Dezenfektan Mendil" } },
  { label: { en: "🧼 Dishwasher pods", tr: "🧼 Bulaşık Makinesi Tableti" }, name: { en: "Dishwasher pods", tr: "Bulaşık Makinesi Tableti" } },
  { label: { en: "🧴 Disposable razors", tr: "🧴 Kullan-At Tıraş Bıçağı" }, name: { en: "Disposable razors", tr: "Tıraş Bıçağı" } },
  { label: { en: "🐾 Dog treats", tr: "🐾 Köpek Ödül Maması" }, name: { en: "Dog treats", tr: "Köpek Ödülü" } },
  { label: { en: "🌿 Dried basil", tr: "🌿 Kuru Fesleğen" }, name: { en: "Dried basil", tr: "Kuru Fesleğen" } },
  { label: { en: "🌿 Dried oregano", tr: "🌿 Kekik (Kuru)" }, name: { en: "Dried oregano", tr: "Kuru Kekik" } },
  { label: { en: "🌿 Dried thyme", tr: "🌿 Kuru Kekik Otu" }, name: { en: "Dried thyme", tr: "Kuru Kekik" } },
  { label: { en: "🐶 Dry dog food", tr: "🐶 Kuru Köpek Maması" }, name: { en: "Dry dog food", tr: "Kuru Köpek Maması" } },
  { label: { en: "🐱 Dry cat food", tr: "🐱 Kuru Kedi Maması" }, name: { en: "Dry cat food", tr: "Kuru Kedi Maması" } },
  { label: { en: "🧼 Dryer sheets", tr: "🧼 Kurutma Makinesi Kokulu Kağıdı" }, name: { en: "Dryer sheets", tr: "Kurutma Kağıdı" } },
  { label: { e: "🧼 Duster refills", tr: "🧼 Toz Alma Püskülü Yedeği" }, name: { en: "Duster refills", tr: "Toz Alıcı Yedek" } },
  { label: { en: "🫘 Edamame", tr: "🫘 Edamame (Taze Soya Fasulyesi)" }, name: { en: "Edamame", tr: "Edamame" } },
  { label: { en: "🫲 Eggplant", tr: "🫲 Patlıcan" }, name: { en: "Eggplant", tr: "Patlıcan" } },
  { label: { en: "🍝 Elbow macaroni", tr: "🍝 Dirsek Makarna" }, name: { en: "Elbow macaroni", tr: "Dirsek Makarna" } },
  { label: { en: "🥤 Energy drinks", tr: "🥤 Enerji İçecekleri" }, name: { en: "Energy drinks", tr: "Enerji İçeceği" } },
  { label: { en: "🧂 Everything bagel seasoning", tr: "🧂 Simit Çeşnisi / Karışık Baharat" }, name: { en: "Everything bagel seasoning", tr: "Simit Çeşnisi" } },
  { label: { en: "🌱 Firm tofu", tr: "🌱 Sert Tofu" }, name: { en: "Firm tofu", tr: "Sert Tofu" } },
  { label: { en: "🌱 Extra-firm tofu", tr: "🌱 Çok Sert Tofu" }, name: { en: "Extra-firm tofu", tr: "Çok Sert Tofu" } },
  { label: { en: "🍾 Extra virgin olive oil", tr: "🍾 Sızma Zeytinyağı" }, name: { en: "Extra virgin olive oil", tr: "Sızma Zeytinyağı" } },
  { label: { en: "🧴 Facial cleanser", tr: "🧴 Yüz Temizleme Jeli" }, name: { en: "Facial cleanser", tr: "Yüz Temizleyici" } },
  { label: { en: "🧻 Facial tissues", tr: "🧻 Kağıt Mendil / Kutu Peçete" }, name: { en: "Facial tissues", tr: "Kutu Peçete" } },
  { label: { en: "🧼 Fabric softener", tr: "🧼 Çamaşır Yumuşatıcı" }, name: { en: "Fabric softener", tr: "Yumuşatıcı" } },
  { label: { en: "🥣 Farro", tr: "🥣 Farro Antik Buğdayı" }, name: { en: "Farro", tr: "Farro Buğdayı" } },
  { label: { en: "🧀 Feta", tr: "🧀 Beyaz Peynir / Feta" }, name: { en: "Feta", tr: "Beyaz Peynir" } },
  { label: { en: "🍝 Fettuccine", tr: "🍝 Fettuccine (Şerit) Makarna" }, name: { en: "Fettuccine", tr: "Fettuccine" } },
  { label: { en: "🧂 Fine sea salt", tr: "🧂 İnce Deniz Tuzu" }, name: { en: "Fine sea salt", tr: "İnce Deniz Tuzu" } },
  { label: { en: "🐟 Fish sauce", tr: "🐟 Balık Sosu" }, name: { en: "Fish sauce", tr: "Balık Sosu" } },
  { label: { en: "🌿 Flat-leaf parsley", tr: "🌿 Maydanoz" }, name: { en: "Flat-leaf parsley", tr: "Maydanoz" } },
  { label: { en: "🥩 Flank steak", tr: "🥩 Böbrek Yatağı Eti / Biftek" }, name: { en: "Flank steak", tr: "Biftek" } },
  { label: { en: "🫘 Flaxseeds", tr: "🫘 Keten Tohumu" }, name: { en: "Flaxseeds", tr: "Keten Tohumu" } },
  { label: { en: "🧼 Floor cleaning solution", tr: "🧼 Yer Yüzey Temizleyici" }, name: { en: "Floor cleaning solution", tr: "Yer Temizleyici" } },
  { label: { en: "🧴 Whitening toothpaste", tr: "🧴 Beyazlatıcı Diş Macunu" }, name: { en: "Whitening toothpaste", tr: "Beyazlatıcı Diş Macunu" } },
  { label: { en: "🍟 French fries", tr: "🍟 Patates Kızartması (Donuk)" }, name: { en: "French fries", tr: "Donuk Patates" } },
  { label: { en: "🥦 Frozen broccoli florets", tr: "🥦 Dondurulmuş Brokoli" }, name: { en: "Frozen broccoli florets", tr: "Dondurulmuş Brokoli" } },
  { label: { en: "🫐 Frozen blueberries", tr: "🫐 Dondurulmuş Yaban Mersini" }, name: { en: "Frozen blueberries", tr: "Dondurulmuş Yaban Mersini" } },
  { label: { en: "🍕 Frozen pizza", tr: "🍕 Dondurulmuş Pizza" }, name: { en: "Frozen pizza", tr: "Dondurulmuş Pizza" } },
  { label: { en: "🌯 Frozen burritos", tr: "🌯 Dondurulmuş Burrito" }, name: { en: "Frozen burritos", tr: "Dondurulmuş Burrito" } },
  { label: { en: "🌽 Frozen corn", tr: "🌽 Dondurulmuş Mısır" }, name: { en: "Frozen corn", tr: "Dondurulmuş Mısır" } },
  { label: { en: "🥭 Frozen mango chunks", tr: "🥭 Dondurulmuş Küp Mango" }, name: { en: "Frozen mango chunks", tr: "Dondurulmuş Mango" } },
  { label: { en: "🥦 Frozen mixed vegetables", tr: "🥦 Dondurulmuş Garnitür / Sebze" }, name: { en: "Frozen mixed vegetables", tr: "Dondurulmuş Karışık Sebze" } },
  { label: { en: "🥦 Frozen peas", tr: "🥦 Dondurulmuş Bezelye" }, name: { en: "Frozen peas", tr: "Dondurulmuş Bezelye" } },
  { label: { en: "🥬 Frozen riced cauliflower", tr: "🥬 Dondurulmuş Karnabahar Pirinci" }, name: { en: "Frozen riced cauliflower", tr: "Karnabahar Pirinci" } },
  { label: { en: "🍓 Frozen strawberries", tr: "🍓 Dondurulmuş Çilek" }, name: { en: "Frozen strawberries", tr: "Dondurulmuş Çilek" } },
  { label: { en: "🍦 Frozen waffles", tr: "🍦 Dondurulmuş Waffle" }, name: { en: "Frozen waffles", tr: "Dondurulmuş Waffle" } },
  { label: { en: "🍦 Frozen yogurt", tr: "🍦 Dondurulmuş Yoğurt" }, name: { en: "Frozen yogurt", tr: "Dondurulmuş Yoğurt" } },
  { label: { en: "🍇 Fruit popsicles", tr: "🍇 Meyveli Buz Parmak" }, name: { en: "Fruit popsicles", tr: "Meyveli Buz" } },
  { label: { en: "🍓 Fruit snacks", tr: "🍓 Meyveli Atıştırmalık / Jelibon" }, name: { en: "Fruit snacks", tr: "Meyveli Atıştırmalık" } },
  { label: { en: "🧻 Gallon ziploc bags", tr: "🧻 Büyük Boy Kilitli Poşet" }, name: { en: "Gallon ziploc bags", tr: "Büyük Kilitli Poşet" } },
  { label: { en: "🧄 Garlic", tr: "🧄 Sarımsak" }, name: { en: "Garlic", tr: "Sarımsak" } },
  { label: { en: "🧂 Garlic powder", tr: "🧂 Sarımsak Tozu" }, name: { en: "Garlic powder", tr: "Sarımsak Tozu" } },
  { label: { en: "🫘 Ginger", tr: "🫘 Zencefil" }, name: { en: "Ginger", tr: "Zencefil" } },
  { label: { en: "🧼 Glass cleaner", tr: "🧼 Cam Temizleyici (Camsil)" }, name: { en: "Glass cleaner", tr: "Cam Temizleyici" } },
  { label: { en: "🧀 Goat cheese", tr: "🧀 Keçi Peyniri" }, name: { en: "Goat cheese", tr: "Keçi Peyniri" } },
  { label: { en: "🧀 Gouda", tr: "🧀 Gouda Peyniri" }, name: { en: "Gouda", tr: "Gouda Peyniri" } },
  { label: { en: "🍇 Grapefruit", tr: "🍇 Greyfurt" }, name: { en: "Grapefruit", tr: "Greyfurt" } },
  { label: { en: "🌱 Grape jelly", tr: "🌱 Üzüm Jolesi / Reçeli" }, name: { en: "開rape jelly", tr: "Üzüm Reçeli" } },
  { label: { en: "🌾 Granulated sugar", tr: "🌾 Toz Şeker" }, name: { en: "Granulated sugar", tr: "Toz Şeker" } },
  { label: { en: "🍿 Granola bars", tr: "🍿 Granola Bar Atıştırmalık" }, name: { en: "Granola bars", tr: "Granola Bar" } },
  { label: { en: "🍏 Granny Smith apples", tr: "🍏 Granny Smith Yeşil Elma" }, name: { en: "Granny Smith apples", tr: "Yeşil Elma" } },
  { label: { en: "🫘 Green beans", tr: "🫘 Taze Fasulye" }, name: { en: "Green beans", tr: "Taze Fasulye" } },
  { label: { en: "🫘 Green lentils", tr: "🫘 Yeşil Mercimek" }, name: { en: "Green lentils", tr: "Yeşil Mercimek" } },
  { label: { en: "🥦 Green peas", tr: "🥦 Bezelye (Taze)" }, name: { en: "Green peas", tr: "Taze Bezelye" } },
  { label: { en: "🍵 Green tea", tr: "🍵 Yeşil Çay" }, name: { en: "Green tea", tr: "Yeşil Çay" } },
  { label: { en: "🥩 Ground beef", tr: "🥩 Dana Kıyma" }, name: { en: "Ground beef", tr: "Dana Kıyma" } },
  { label: { en: "☕ Ground coffee", tr: "☕ Filtre / Öğütülmüş Kahve" }, name: { en: "Ground coffee", tr: "Öğütülmüş Kahve" } },
  { label: { en: "🥩 Ground pork", tr: "🥩 Domuz Kıyması" }, name: { en: "Ground pork", tr: "Domuz Kıyması" } },
  { label: { en: "🥩 Ground turkey", tr: "🥩 Hindi Kıyması" }, name: { en: "Ground turkey", tr: "Hindi Kıyması" } },
  { label: { en: "🌶️ Ground Cinnamon", tr: "🌶️ Toz Tarçın" }, name: { en: "Ground Cinnamon", tr: "Toz Tarçın" } },
  { label: { en: "🌶️ Ground cumin", tr: "🌶️ Kimyon" }, name: { en: "Ground cumin", tr: "Kimyon" } },
  { label: { en: "🌶️ Ground ginger", tr: "🌶️ Toz Zencefil" }, name: { en: "Ground ginger", tr: "Toz Zencefil" } },
  { label: { en: "🥑 Guacamole", tr: "🥑 Avokado Sosu (Guacamole)" }, name: { en: "Guacamole", tr: "Guacamole" } },
  { label: { en: "🍫 Gummy bears", tr: "🍫 Jelibon / Ayıcık" }, name: { en: "Gummy bears", tr: "Jelibon" } },
  { label: { en: "🐟 Halibut", tr: "🐟 Atlantik Mezgit Balığı" }, name: { en: "Halibut", tr: "Halibut Balığı" } },
  { label: { en: "🥛 Half-and-half", tr: "🥛 Süt-Krema Karışımı" }, name: { en: "Half-and-half", tr: "Süt-Krema Karışımı" } },
  { label: { en: "🧴 Hand sanitizer", tr: "🧴 El Dezenfektanı" }, name: { en: "Hand sanitizer", tr: "El Dezenfektanı" } },
  { label: { en: "🥔 Hash browns", tr: "🥔 Mücver Patates Kızartması" }, name: { en: "Hash browns", tr: "Mücver Patates" } },
  { label: { en: "🥑 Hass avocados", tr: "🥑 Hass Avokado" }, name: { en: "Hass avocados", tr: "Hass Avokado" } },
  { label: { en: "🥛 Heavy whipping cream", tr: "🥛 Yoğun Sıvı Krema" }, name: { en: "Heavy whipping cream", tr: "Sıvı Krema" } },
  { label: { en: "🍿 Honey nut cereal", tr: "🍿 Ballı Kuruyemişli Gevrek" }, name: { en: "Honey nut cereal", tr: "Ballı Gevrek" } },
  { label: { en: "🍏 Honeycrisp apples", tr: "🍏 Honeycrisp Tatlı Elma" }, name: { en: "Honeycrisp apples", tr: "Tatlı Elma" } },
  { label: { en: "🍉 Honeydew", tr: "🍉 Sarı Kavun" }, name: { en: "Honeydew", tr: "Sarı Kavun" } },
  { label: { en: "🔥 Hot sauce", tr: "🔥 Acı Sos" }, name: { en: "Hot sauce", tr: "Acı Sos" } },
  { label: { en: "🥑 Hummus", tr: "🥑 Humus" }, name: { en: "Hummus", tr: "Humus" } },
  { label: { en: "🥬 Iceberg", tr: "🥬 Aysberg / Göbek Marul" }, name: { en: "Iceberg", tr: "Göbek Marul" } },
  { label: { en: "🍦 Ice cream sandwiches", tr: "🍦 Sandviç Dondurma" }, name: { en: "Ice cream sandwiches", tr: "Sandviç Dondurma" } },
  { label: { en: "☕ Instant coffee", tr: "☕ Hazır Neskafe" }, name: { en: "Instant coffee", tr: "Hazır Kahve" } },
  { label: { en: "🥣 Instant oatmeal", tr: "🥣 Hızlı Yulaf Ezmesi" }, name: { en: "Instant oatmeal", tr: "Hızlı Yulaf Ezmesi" } },
  { label: { en: "🌶️ Jalapeños", tr: "🌶️ Jalapeno Biberi" }, name: { en: "Jalapeños", tr: "Jalapeno Biberi" } },
  { label: { en: "🍚 Jasmine rice", tr: "🍚 Yasemin Kokulu Pirinç" }, name: { en: "Jasmine rice", tr: "Yasemin Pirinç" } },
  { label: { en: "☕ K-cups", tr: "☕ K-Cup Kapsül Kahve" }, name: { en: "K-cups", tr: "Kapsül Kahve" } },
  { label: { en: "🥬 Kale", tr: "🥬 Kale / Kıvırcık Lahana" }, name: { en: "Kale", tr: "Kale Lahanası" } },
  { label: { en: "🥛 Kefir", tr: "🥛 Kefir" }, name: { en: "Kefir", tr: "Kefir" } },
  { label: { en: "🍅 Ketchup", tr: "🍅 Ketçap" }, name: { en: "Ketchup", tr: "Ketçap" } },
  { label: { en: "🫘 Kidney beans", tr: "🫘 Barbunya" }, name: { en: "Kidney beans", tr: "Barbunya" } },
  { label: { en: "🧼 Kitchen sponges", tr: "🧼 Bulaşık Süngeri" }, name: { en: "Kitchen sponges", tr: "Bulaşık Süngeri" } },
  { label: { en: "🥝 Kiwi", tr: "🥝 Kivi" }, name: { en: "Kiwi", tr: "Kivi" } },
  { label: { en: "🧂 Kosher salt", tr: "🧂 Kaşer / İri Salamura Tuzu" }, name: { en: "Kosher salt", tr: "İri Tuz" } },
  { label: { en: "🥩 Lamb chops", tr: "🥩 Kuzu Pirzola" }, name: { en: "Lamb chops", tr: "Kuzu Pirzola" } },
  { label: { en: "🥚 Large white eggs", tr: "🥚 Büyük Boy Beyaz Yumurta" }, name: { en: "Large white eggs", tr: "Büyük Beyaz Yumurta" } },
  { label: { en: "🍝 Lasagna sheets", tr: "🍝 Lazanya Yaprakları" }, name: { en: "Lasagna sheets", tr: "Lazanya Yaprağı" } },
  { label: { en: "🧼 Laundry detergent liquid", tr: "🧼 Sıvı Çamaşır Deterjanı" }, name: { en: "Laundry detergent liquid", tr: "Sıvı Çamaşır Deterjanı" } },
  { label: { en: "🧼 Laundry pods", tr: "🧼 Çamaşır Deterjan Kapsülü" }, name: { en: "Laundry pods", tr: "Çamaşır Kapsülü" } },
  { label: { en: "🧃 Lemonade", tr: "🧃 Limonata" }, name: { en: "Lemonade", tr: "Limonata" } },
  { label: { en: "🥬 Lemons", tr: "🥬 Limon" }, name: { en: "Lemons", tr: "Limon" } },
  { label: { en: "🌿 Lemongrass", tr: "🌿 Limon Otu" }, name: { en: "Lemongrass", tr: "Limon Otu" } },
  { label: { en: "🥬 Limes", tr: "🥬 Misket Limonu (Yeşil)" }, name: { en: "Limes", tr: "Misket Limonu" } },
  { label: { en: "🥚 Liquid egg whites", tr: "🥚 Sıvı Yumurta Akı" }, name: { en: "Liquid egg whites", tr: "Sıvı Yumurta Akı" } },
  { label: { en: "🧼 Liquid dish soap", tr: "🧼 Elde Bulaşık Deterjanı (Pril)" }, name: { en: "Liquid dish soap", tr: "Bulaşık Deterjanı" } },
  { label: { en: "🧴 Liquid hand soap", tr: "🧴 Sıvı El Sabunu" }, name: { en: "Liquid hand soap", tr: "Sıvı El Sabunu" } },
  { label: { en: "🦞 Lobster tails", tr: "🦞 Istakoz Kuyruğu" }, name: { en: "Lobster tails", tr: "Istakoz Kuyruğu" } },
  { label: { en: "🐟 Mahi-mahi", tr: "🐟 Mahi-Mahi (Yabancı Açık Deniz Balığı)" }, name: { en: "Mahi-mahi", tr: "Mahi-Mahi" } },
  { label: { en: "🍍 Mangos", tr: "🍍 Mango" }, name: { en: "Mangos", tr: "Mango" } },
  { label: { en: "🥞 Maple syrup", tr: "🥞 Akçaağaç Şurubu" }, name: { en: "Maple syrup", tr: "Akçaağaç Şurubu" } },
  { label: { en: "🧈 Margarine", tr: "🧈 Margarin" }, name: { en: "Margarine", tr: "Margarin" } },
  { label: { en: "🥫 Marinara sauce", tr: "🥫 Marinara (Domates) Sosu" }, name: { en: "Marinara sauce", tr: "Marinara Sos" } },
  { label: { en: "🧉 Matcha powder", tr: "🧉 Maça (Matcha) Çayı Tozu" }, name: { en: "Matcha powder", tr: "Matcha Tozu" } },
  { label: { en: "¼ Mayonnaise", tr: "¼ Mayonez" }, name: { en: "Mayonnaise", tr: "Mayonez" } },
  { label: { en: "🧼 Microfiber cloths", tr: "🧼 Mikrofiber Temizlik Bezi" }, name: { en: "Microfiber cloths", tr: "Mikrofiber Bez" } },
  { label: { en: "🥛 Milk chocolate bars", tr: "🥛 Sütlü Baton Çikolata" }, name: { en: "Milk chocolate bars", tr: "Sütlü Çikolata" } },
  { label: { en: "🌿 Mint", tr: "🌿 Nane (Taze)" }, name: { en: "Mint", tr: "Taze Nane" } },
  { label: { en: "🌾 Molasses", tr: "🌾 Pekmez" }, name: { en: "Molasses", tr: "Pekmez" } },
  { label: { en: "🧀 Monterey Jack", tr: "🧀 Monterey Jack Peyniri" }, name: { en: "Monterey Jack", tr: "Monterey Jack Peyniri" } },
  { label: { en: "🧴 Moisturizer", tr: "🧴 Nemlendirici Krem" }, name: { en: "Moisturizer", tr: "Nemlendirici Krem" } },
  { label: { en: "🧴 Mouthwash", tr: "🧴 Ağız Çalkalama Suyu" }, name: { en: "Mouthwash", tr: "Ağız Çalkalama Suyu" } },
  { label: { en: "🧀 Mozzarella", tr: "🧀 Mozarella Peyniri" }, name: { en: "Mozzarella", tr: "Mozarella" } },
  { label: { en: "🍄 Mushroom (White Button)", tr: "🍄 Kültür Mantarı (Beyaz)" }, name: { en: "White button mushrooms", tr: "Kültür Mantarı" } },
  { label: { en: "🌶️ Nutmeg", tr: "🌶️ Muskat Cevizi" }, name: { en: "Nutmeg", tr: "Muskat Cevizi" } },
  { label: { en: "🍊 Navel oranges", tr: "🍊 Sıkmalık Portakal" }, name: { en: "Navel oranges", tr: "Sıkmalık Portakal" } },
  { label: { en: "🍑 Nectarines", tr: "🍑 Nektarin" }, name: { en: "Nectarines", tr: "Nektarin" } },
  { label: { en: "🥩 New York strip", tr: "🥩 New York Strip Kontrfile Biftek" }, name: { en: "New York strip", tr: "Kontrfile Biftek" } },
  { label: { en: "🌱 Oat milk", tr: "🌱 Yulaf Sütü" }, name: { en: "Oat milk", tr: "Yulaf Sütü" } },
  { label: { en: "🧴 Oatmeal baby cereal", tr: "🧴 Yulaflı Bebek Kaşık Maması" }, name: { en: "Oatmeal baby cereal", tr: "Yulaflı Bebek Maması" } },
  { label: { en: "🫘 Okra", tr: "🫘 Bamya" }, name: { en: "Okra", tr: "Bamya" } },
  { label: { en: "🫘 Sliced black olives", tr: "🫘 Dilimlenmiş Siyah Zeytin" }, name: { en: "Sliced black olives", tr: "Dilimlenmiş Siyah Zeytin" } },
  { label: { en: "🫘 Onion powder", tr: "🫘 Soğan Tozu" }, name: { en: "Onion powder", tr: "Soğan Tozu" } },
  { label: { en: "🧃 Orange juice", tr: "🧃 Portakal Suyu" }, name: { en: "Orange juice", tr: "Portakal Suyu" } },
  { label: { en: "🌿 Oregano", tr: "🌿 Kekik (Yemeklik)" }, name: { en: "Oregano", tr: "Kekik" } },
  { label: { en: "🍄 Oyster mushrooms", tr: "🍄 İstiridye Mantarı" }, name: { en: "Oyster mushrooms", tr: "İstiridye Mantarı" } },
  { label: { en: "🥩 Pancetta", tr: "🥩 Pançeta / İtalyan Pastırması" }, name: { en: "Pancetta", tr: "Pançeta" } },
  { label: { en: "🥞 Pancake mix", tr: "🥞 Hazır Pankek Harcı" }, name: { en: "Pancake mix", tr: "Pankek Harcı" } },
  { label: { en: "🥭 Papayas", tr: "🥭 Papaya" }, name: { en: "Papayas", tr: "Papaya" } },
  { label: { en: "🧻 Paper bowls", tr: "🧻 Kağıt Kase" }, name: { en: "Paper bowls", tr: "Kağıt Kase" } },
  { label: { en: "🧻 Paper napkins", tr: "🧻 Kağıt Peçete" }, name: { en: "Paper napkins", tr: "Kağıt Peçete" } },
  { label: { en: "🧻 Paper plates", tr: "🧻 Kağıt Tabak" }, name: { en: "Paper plates", tr: "Kağıt Tabak" } },
  { label: { en: "🧻 Paper towels", tr: "🧻 Kağıt Havlu" }, name: { en: "Paper towels", tr: "Kağıt Havlu" } },
  { label: { en: "🧻 Parchment paper", tr: "🧻 Yağlı Pişirme Kağıdı" }, name: { en: "Parchment paper", tr: "Pişirme Kağıdı" } },
  { label: { en: "🧀 Parmesan", tr: "🧀 Parmesan Peyniri" }, name: { en: "Parmesan", tr: "Parmesan" } },
  { label: { en: "🫘 Parsnips", tr: "🫘 Yaban Havucu" }, name: { en: "Parsnips", tr: "Yaban Havucu" } },
  { label: { en: "🍑 Peaches", tr: "🍑 Şeftali" }, name: { en: "Peaches", tr: "Şeftali" } },
  { label: { en: "🥜 Peanuts", tr: "🥜 Yer Fıstığı" }, name: { en: "Peanuts", tr: "Yer Fıstığı" } },
  { label: { en: "🍝 Penne", tr: "🍝 Kalem (Penne) Makarna" }, name: { en: "Penne", tr: "Penne Makarna" } },
  { label: { en: "🧀 Pepper jack", tr: "🧀 Pepper Jack (Acılı) Peyniri" }, name: { en: "Pepper jack", tr: "Pepper Jack Peyniri" } },
  { label: { en: "🍕 Pepperoni", tr: "🍕 Pepperoni Sucuk" }, name: { en: "Pepperoni", tr: "Pepperoni" } },
  { label: { en: "🥑 Pesto", tr: "🥑 Pesto Sosu" }, name: { en: "Pesto", tr: "Pesto Sosu" } },
  { label: { en: "🦴 Pet waste bags", tr: "🦴 Evcil Hayvan Atık Torbası" }, name: { en: "Pet waste bags", tr: "Atık Poşeti" } },
  { label: { en: "🍍 Pineapples", tr: "🍍 Ananas" }, name: { en: "Pineapples", tr: "Ananas" } },
  { label: { en: "🫘 Pinto beans", tr: "🫘 Barbunya Fasulyesi" }, name: { en: "Pinto beans", tr: "Barbunya" } },
  { label: { en: "🥜 Pistachios", tr: "🥜 Antep Fıstığı" }, name: { en: "Pistachios", tr: "Antep Fıstığı" } },
  { label: { en: "🍿 Pita chips", tr: "🍿 Lavaş / Pide Cipsi" }, name: { en: "Pita chips", tr: "Pide Cipsi" } },
  { label: { en: "🧀 Plain Greek yogurt", tr: "🧀 Süzme Yoğurt" }, name: { en: "Plain Greek yogurt", tr: "Süzme Yoğurt" } },
  { label: { en: "🧻 Plastic cling wrap", tr: "🧻 Streç Film" }, name: { en: "Plastic cling wrap", tr: "Streç Film" } },
  { label: { en: "🧈 Plant-based butter", tr: "🧈 Bitkisel Vegan Tereyağı" }, name: { en: "Plant-based butter", tr: "Bitkisel Tereyağı" } },
  { label: { en: "🍑 Plums", tr: "🍑 Erik" }, name: { en: "Plums", tr: "Erik" } },
  { label: { en: "🍎 Pomegranates", tr: "🍎 Nar" }, name: { en: "Pomegranates", tr: "Nar" } },
  { label: { en: "🍿 Popcorn", tr: "🍿 Patlamış Mısır" }, name: { en: "Popcorn", tr: "Patlamış Mısır" } },
  { label: { en: "🥩 Pork ribs", tr: "🥩 Domuz Kaburga" }, name: { en: "Pork ribs", tr: "Domuz Kaburga" } },
  { label: { en: "🥩 Pork chops", tr: "🥩 Domuz Pirzola" }, name: { en: "Pork chops", tr: "Domuz Pirzola" } },
  { label: { en: "🥩 Pork rinds", tr: "🥩 Domuz Derisi Cipsi" }, name: { en: "Pork rinds", tr: "Domuz Cipsi" } },
  { label: { en: "🥩 Pork tenderloin", tr: "🥩 Domuz Bonfile" }, name: { en: "Pork tenderloin", tr: "Domuz Bonfile" } },
  { label: { en: "🍄 Portobello", tr: "🍄 Portobello Mantarı" }, name: { en: "Portobello", tr: "Portobello" } },
  { label: { en: "🥔 Potato chips", tr: "🥔 Patates Cipsi" }, name: { en: "Potato chips", tr: "Patates Cipsi" } },
  { label: { en: "🥔 Potstickers", tr: "🥔 Çin Mantısı / Gyoza" }, name: { en: "Potstickers", tr: "Çin Mantısı" } },
  { label: { en: "🌾 Powdered sugar", tr: "🌾 Pudra Şekeri" }, name: { en: "Powdered sugar", tr: "Pudra Şekeri" } },
  { label: { en: "🍿 Pretzels", tr: "🍿 Kraker / Pretzel" }, name: { en: "Pretzels", tr: "Pretzel" } },
  { label: { en: "🍿 Protein bars", tr: "🍿 Protein Bar" }, name: { en: "Protein bars", tr: "Protein Bar" } },
  { label: { en: "🥩 Prosciutto", tr: "🥩 İtalyan Kuru Füme Eti" }, name: { en: "Prosciutto", tr: "Kuru Füme Et" } },
  { label: { en: "🧀 Provolone", tr: "🧀 Provolone Peyniri" }, name: { en: "Provolone", tr: "Provolone" } },
  { label: { en: "🫘 Pumpkin seeds", tr: "🫘 Kabak Çekirdeği" }, name: { en: "Pumpkin seeds", tr: "Kabak Çekirdeği" } },
  { label: { en: "🧴 Q-tips", tr: "🧴 Kulak Temizleme Çöpü" }, name: { en: "Q-tips", tr: "Kulak Çöpü" } },
  { label: { en: "🧻 Quart ziploc bags", tr: "🧻 Orta Boy Kilitli Poşet" }, name: { en: "Quart ziploc bags", tr: "Orta Kilitli Poşet" } },
  { label: { en: "🥣 Quinoa", tr: "🥣 Kinoa" }, name: { en: "Quinoa", tr: "Kinoa" } },
  { label: { en: "🫘 Radishes", tr: "🫘 Turp" }, name: { en: "Radishes", tr: "Turp" } },
  { label: { en: "🍜 Ramen noodles", tr: "🍜 Ramen Eriştesi / Noodle" }, name: { en: "Ramen noodles", tr: "Ramen Eriştesi" } },
  { label: { en: "🍇 Raspberries", tr: "🍇 Ahududu / Frambuaz" }, name: { en: "Raspberries", tr: "Ahududu" } },
  { label: { en: "🥜 Raw almonds", tr: "🥜 Çiğ Badem" }, name: { en: "Raw almonds", tr: "Çiğ Badem" } },
  { label: { en: "🫘 Red lentils", tr: "🫘 Kırmızı Mercimek" }, name: { en: "Red lentils", tr: "Kırmızı Mercimek" } },
  { label: { en: "🫘 Red onions", tr: "🫘 Mor / Kırmızı Soğan" }, name: { en: "Red onions", tr: "Kırmızı Soğan" } },
  { label: { en: "¼ Relish", tr: "¼ Kornişon Turşu Sosu (Relish)" }, name: { en: "Relish", tr: "Turşu Sosu" } },
  { label: { en: "🥩 Ribeye steak", tr: "🥩 Antrikot Biftek" }, name: { en: "Ribeye steak", tr: "Antrikot" } },
  { label: { en: "🧀 Ricotta", tr: "🧀 Rikotta (Lor) Peyniri" }, name: { en: "Ricotta", tr: "Rikotta Peyniri" } },
  { label: { en: "🍾 Rice vinegar", tr: "🍾 Pirinç Sirkesi" }, name: { en: "Rice vinegar", tr: "Pirinç Sirkesi" } },
  { label: { en: "🍿 Rice cakes", tr: "🍿 Pirinç Patlağı Krakeri" }, name: { en: "Rice cakes", tr: "Pirinç Patlağı" } },
  { label: { en: "🍜 Rice noodles", tr: "🍜 Pirinç Eriştesi" }, name: { en: "Rice noodles", tr: "Pirinç Eriştesi" } },
  { label: { en: "🍝 Rigatoni", tr: "🍝 Rigatoni (Tırtıklı Kalın) Maķarna" }, name: { en: "Rigatoni", tr: "Rigatoni" } },
  { label: { en: "🍿 Ritz crackers", tr: "🍿 Ritz Tuzlu Kraker" }, name: { en: "Ritz crackers", tr: "Ritz Kraker" } },
  { label: { en: "🥩 Roast beef", tr: "🥩 Rozbif (Pişmiş Dana Füme)" }, name: { en: "Roast beef", tr: "Rozbif" } },
  { label: { en: "🥣 Rolled oats", tr: "🥣 Yulaf Ezmesi" }, name: { en: "Rolled oats", tr: "Yulaf Ezmesi" } },
  { label: { en: "🥬 Romaine", tr: "🥬 Yedikule / Marul" }, name: { en: "Romaine", tr: "Marul" } },
  { label: { en: "🍅 Roma tomatoes", tr: "🍅 Roma / Oval Domates" }, name: { en: "Roma tomatoes", tr: "Roma Domates" } },
  { label: { en: "🌿 Rosemary", tr: "🌿 Biberiye" }, name: { en: "Rosemary", tr: "Biberiye" } },
  { label: { en: "🧼 Rubber gloves", tr: "🧼 Temizlik Bulaşık Eldiveni" }, name: { en: "Rubber gloves", tr: "Temizlik Eldiveni" } },
  { label: { en: "🥔 Russet potatoes", tr: "🥔 Büyük Fırınlık Patates" }, name: { en: "Russet potatoes", tr: "Fırınlık Patates" } },
  { label: { en: "🥩 Salami", tr: "🥩 Salam / Sucuk" }, name: { en: "Salami", tr: "Salam" } },
  { label: { en: "🥗 Salsa", tr: "🥗 Salsa Sosu" }, name: { en: "Salsa", tr: "Salsa Sosu" } },
  { label: { en: "🍿 Saltine crackers", tr: "🍿 Tuzlu Kare Kraker" }, name: { en: "Saltine crackers", tr: "Tuzlu Kraker" } },
  { label: { en: "🍿 Sandwich cookies", tr: "🍿 Kremalı Sandviç Bisküvi (Oreo vb)" }, name: { en: "Sandwich cookies", tr: "Sandviç Bisküvi" } },
  { label: { en: "🧻 Sandwich bags", tr: "🧻 Kilitli Sandviç Poşeti" }, name: { en: "Sandwich bags", tr: "Sandviç Poşeti" } },
  { label: { en: "🧻 Sanitary pads", tr: "🧻 Hijyenik Ped" }, name: { en: "Sanitary pads", tr: "Hijyenik Ped" } },
  { label: { en: "🥫 Sardines", tr: "🥫 Sardalya Konservesi" }, name: { en: "Sardines", tr: "Sardalya Konservesi" } },
  { label: { en: "🦪 Sea scallops", tr: "🦪 Deniz Tarğı (Scallop)" }, name: { en: "Sea scallops", tr: "Deniz Tarakları" } },
  { label: { en: "🧼 Scoring pads", tr: "🧼 Tel / Ovma Süngeri" }, name: { en: "Scoring pads", tr: "Ovma Süngeri" } },
  { label: { en: "🧼 Scrub brushes", tr: "🧼 Temizlik Fırçası" }, name: { en: "Scrub brushes", tr: "Temizlik Fırçası" } },
  { label: { en: "🌱 Seitan", tr: "🌱 Söytan (Ete Alternatif Buğday Gluteni)" }, name: { en: "Seitan", tr: "Seitan" } },
  { label: { en: "💧 Seltzer", tr: "💧 Aromasız Gazlı Su / Seltzer" }, name: { en: "Seltzer", tr: "Seltzer" } },
  { label: { en: "🍾 Sesame oil", tr: "🍾 Susam Yağı" }, name: { en: "Sesame oil", tr: "Susam Yağı" } },
  { label: { en: "🫘 Shallots", tr: "🫘 Arpacık Soğanı" }, name: { en: "Shallots", tr: "Arpacık Soğanı" } },
  { label: { en: "🧴 Shampoo", tr: "🧴 Şampuan" }, name: { en: "Shampoo", tr: "Şampuan" } },
  { label: { en: "🧴 Shaving cream", tr: "🧴 Tıraş Köpüğü" }, name: { en: "Shaving cream", tr: "Tıraş Köpüğü" } },
  { label: { en: "🧴 Shaving gel", tr: "🧴 Tıraş Jeli" }, name: { en: "Shaving gel", tr: "Tıraş Jeli" } },
  { label: { en: "🍄 Shiitake", tr: "🍄 Şitaki Mantarı" }, name: { en: "Shiitake", tr: "Şitaki Mantarı" } },
  { label: { en: "🥛 Skim milk", tr: "🥛 Yağsız Süt" }, name: { en: "Skim milk", tr: "Yağsız Süt" } },
  { label: { en: "🥩 Sliced turkey breast", tr: "🥩 Dilimlenmiş Hindi Göğsü Şarküteri" }, name: { en: "Sliced turkey breast", tr: "Hindi Şarküteri" } },
  { label: { en: "🌶️ Smoked paprika", tr: "🌶️ Tütsülenmiş Kırmızı Toz Biber" }, name: { en: "Smoked paprika", tr: "Tütsülü Toz Biber" } },
  { label: { en: "🥬 Sour cream", tr: "🥬 Ekşi Krema" }, name: { en: "Sour cream", tr: "Ekşi Krema" } },
  { label: { en: "🌱 Soy milk", tr: "🌱 Soya Sütü" }, name: { en: "Soy milk", tr: "Soya Sütü" } },
  { label: { en: "🐟 Soy sauce", tr: "🐟 Soya Sosu" }, name: { en: "Soy sauce", tr: "Soya Sosu" } },
  { label: { en: "🍝 Spaghetti", tr: "🍝 Spagetti" }, name: { en: "Spaghetti", tr: "Spagetti" } },
  { label: { en: "💧 Sparkling water", tr: "💧 Maden Suyu / Mineralli Gazlı Su" }, name: { en: "Sparkling water", tr: "Maden Suyu" } },
  { label: { en: "🥬 Spinach", tr: "🥬 Ispanak" }, name: { en: "Spinach", tr: "Ispanak" } },
  { label: { en: "𫛞 Split peas", tr: "𫛞 Kırık Bezelye" }, name: { en: "Split peas", tr: "Kırık Bezelye" } },
  { label: { en: "🔥 Sriracha", tr: "🔥 Sriracha (Acı Biber) Sosu" }, name: { en: "Sriracha", tr: "Sriracha Sosu" } },
  { label: { en: "🧼 Stain remover spray", tr: "🧼 Leke Çıkarıcı Sprey" }, name: { en: "Stain remover spray", tr: "Leke Çıkarıcı" } },
  { label: { en: "🥣 Steel-cut oats", tr: "🥣 İskoç / İri Kırılmış Yulaf" }, name: { en: "Steel-cut oats", tr: "İri Kırılmış Yulaf" } },
  { label: { en: "🍓 Strawberries", tr: "🍓 Çilek" }, name: { en: "Strawberries", tr: "Çilek" } },
  { label: { en: "🫘 Sugar snap peas", tr: "🫘 Tatlı Bezelye Çıtırcık" }, name: { en: "Sugar snap peas", tr: "Tatlı Bezelye" } },
  { label: { en: "🫘 Sunflower seeds", tr: "🫘 Ay Çekirdeği" }, name: { en: "Sunflower seeds", tr: "Ay Çekirdeği" } },
  { label: { en: "🌽 Sweet corn", tr: "🌽 Tatlı Mısır" }, name: { en: "Sweet corn", tr: "Tatlı Mısır" } },
  { label: { en: "🔥 Sweet chili sauce", tr: "🔥 Tatlı Acı Biber Sosu" }, name: { en: "Sweet chili sauce", tr: "Tatlı Acı Sos" } },
  { label: { en: "🥔 Sweet potatoes", tr: "🥔 Tatlı Patates" }, name: { en: "Sweet potatoes", tr: "Tatlı Patates" } },
  { label: { en: "🥬 Swiss chard", tr: "🥬 Pazı" }, name: { en: "Swiss chard", tr: "Pazı" } },
  { label: { en: "🧀 Swiss", tr: "🧀 İsviçre Peyniri (Gravyer)" }, name: { en: "Swiss", tr: "İsviçre Peyniri" } },
  { label: { en: "🧻 Tall kitchen trash bags", tr: "🧻 Büyük Boy Mutfak Çöp Poşeti" }, name: { en: "Tall kitchen trash bags", tr: "Mutfak Çöp Poşeti" } },
  { label: { en: "🐟 Tamari", tr: "🐟 Tamari (Glutensiz Soya Sosu)" }, name: { en: "Tamari", tr: "Tamari Sosu" } },
  { label: { en: "🌮 Taquitos", tr: "🌮 Çıtır Rulo Takito" }, name: { en: "Taquitos", tr: "Takito" } },
  { label: { en: "🍟 Tater tots", tr: "🍟 Silindir Patates Kızartması" }, name: { en: "Tater tots", tr: "Silindir Patates" } },
  { label: { en: "🧴 Tampons", tr: "🧴 Tampon" }, name: { en: "Tampons", tr: "Tampon" } },
  { label: { en: "🌱 Tempeh", tr: "🌱 Tempeh (Fermente Soya Alternatifi)" }, name: { en: "Tempeh", tr: "Tempeh" } },
  { label: { en: "🐟 Teriyaki sauce", tr: "🐟 Teriyaki Sosu" }, name: { en: "Teriyaki sauce", tr: "Teriyaki Sos" } },
  { label: { en: "🌿 Thyme", tr: "🌿 Dağ Kekiği" }, name: { en: "Thyme", tr: "Dağ Kekiği" } },
  { label: { en: "🐟 Tilapia", tr: "🐟 Tilapya Balığı" }, name: { en: "Tilapia", tr: "Tilapya Balığı" } },
  { label: { en: "🧻 Toilet paper", tr: "🧻 Tuvalet Kağıdı" }, name: { en: "Toilet paper", tr: "Tuvalet Kağıdı" } },
  { label: { en: "🧼 Toilet bowl cleaner", tr: "🧼 Klozet Temizleyici (Asetonlu/Asitli)" }, name: { en: "Toilet bowl cleaner", tr: "Klozet Temizleyici" } },
  { label: { en: "🥫 Tomato juice", tr: "🥫 Domates Suyu" }, name: { en: "Tomato juice", tr: "Domates Suyu" } },
  { label: { en: "🥫 Tomato paste", tr: "🥫 Domates Salçası" }, name: { en: "Tomato paste", tr: "Domates Salçası" } },
  { label: { en: "🥫 Tomato sauce", tr: "🥫 Domates Sosu" }, name: { en: "Tomato sauce", tr: "Domates Sosu" } },
  { label: { en: "🥫 Tomato soup", tr: "🥫 Domates Çorbası" }, name: { en: "Tomato soup", tr: "Domates Çorbası" } },
  { label: { en: "🍿 Tortilla chips", tr: "🍿 Mısır Cipsi / Tortilla" }, name: { en: "Tortilla chips", tr: "Tortilla Cipsi" } },
  { label: { en: "🫓 Tortilla", tr: "🫓 Lavaş / Tortilla Ekmeği" }, name: { en: "Tortilla", tr: "Tortilla" } },
  { label: { en: "🧴 Toothbrushes", tr: "🧴 Diş Fırçası" }, name: { en: "Toothbrushes", tr: "Diş Fırçası" } },
  { label: { en: "🐟 Trout", tr: "🐟 Alabalık" }, name: { en: "Trout", tr: "Alabalık" } },
  { label: { en: "🐟 Tuna steaks", tr: "🐟 Dilim Fillet Ton Balığı" }, name: { en: "Tuna steaks", tr: "Fileto Ton" } },
  { label: { en: "🫘 Turnips", tr: "🫘 Şalgam / Şalgam Turpu" }, name: { en: "Turnips", tr: "Şalgam" } },
  { label: { en: "🫘 Turmeric", tr: "🫘 Zerdeçal" }, name: { en: "Turmeric", tr: "Zerdeçal" } },
  { label: { en: "🥛 Unsalted butter", tr: "🥛 Tuzsuz Tereyağı" }, name: { en: "Unsalted butter", tr: "Tuzsuz Tereyağı" } },
  { label: { en: "🍦 Vanilla ice cream", tr: "🍦 Vanilyalı Dondurma" }, name: { en: "Vanilla ice cream", tr: "Vanilyalı Dondurma" } },
  { label: { en: "🌾 Vanilla extract", tr: "🌾 Vanilya Özütü" }, name: { en: "Vanilla extract", tr: "Vanilya Özütü" } },
  { label: { en: "🥛 Vanilla yogurt", tr: "🥛 Vanilyalı Yoğurt" }, name: { en: "Vanilla yogurt", tr: "Vanilyalı Yoğurt" } },
  { label: { en: "🥣 Vegetable broth", tr: "🥣 Sebze Suyu" }, name: { en: "Vegetable broth", tr: "Sebze Suyu" } },
  { label: { en: "🍾 Vegetable oil", tr: "🍾 Bitkisel Sıvı Yağ" }, name: { en: "Vegetable oil", tr: "Sıvı Yağ" } },
  { label: { en: "🥜 Walnuts", tr: "🥜 Ceviz" }, name: { en: "Walnuts", tr: "Ceviz" } },
  { label: { en: "🍉 Watercress", tr: "🍉 Terotu / Su Teresi" }, name: { en: "Watercress", tr: "Su Teresi" } },
  { label: { en: "🍉 Watermelon", tr: "🍉 Karpuz" }, name: { en: "Watermelon", tr: "Karpuz" } },
  { label: { en: "🧻 Wax paper", tr: "🧻 Balmumu Pişirme Kağıdı" }, name: { en: "Wax paper", tr: "Balmumu Kağıdı" } },
  { label: { en: "🐾 Wet cat food", tr: "🐾 Yaş Kedi Maması" }, name: { en: "Wet cat food", tr: "Yaş Kedi Maması" } },
  { label: { en: "🐾 Wet dog food", tr: "🐾 Yaş Köpek Maması" }, name: { en: "Wet dog food", tr: "Yaş Köpek Maması" } },
  { label: { en: "🍿 Wheat crackers", tr: "🍿 Tam Buğdaylı Kraker" }, name: { en: "Wheat crackers", tr: "Tam Buğdaylı Kraker" } },
  { label: { en: "🍾 White cleaning vinegar", tr: "🍾 Beyaz Temizlik Sirkesi" }, name: { en: "White cleaning vinegar", tr: "Beyaz Temizlik Sirkesi" } },
  { label: { en: "🦪 White shrimp", tr: "🦪 Beyaz Karides" }, name: { en: "White shrimp", tr: "Beyaz Karides" } },
  { label: { en: "🍾 White vinegar", tr: "🍾 Beyaz Sirke" }, name: { en: "White vinegar", tr: "Beyaz Sirke" } },
  { label: { en: "🍗 Whole chicken", tr: "🍗 Bütün Tavuk" }, name: { en: "Whole chicken", tr: "Bütün Tavuk" } },
  { label: { en: "🥛 Whole milk", tr: "🥛 Tam Yağlı Süt" }, name: { en: "Whole milk", tr: "Tam Yağlı Süt" } },
  { label: { en: "🌾 Whole wheat flour", tr: "🌾 Tam Buğday Unu" }, name: { en: "Whole wheat flour", tr: "Tam Buğday Unu" } },
  { label: { en: "🧼 Wood polish", tr: "🧼 Ahşap Cilası / Mobilya Parlatıcı" }, name: { en: "Wood polish", tr: "Ahşap Cilası" } },
  { label: { en: "🐟 Worcestershire sauce", tr: "🐟 Vorçester (Worcestershire) Sosu" }, name: { en: "Worcestershire sauce", tr: "Worcestershire Sosu" } },
  { label: { en: "🫘 Yellow onions", tr: "🫘 Yemeklik Kuru Soğan" }, name: { en: "Yellow onions", tr: "Kuru Soğan" } },
  { label: { en: "🫘 Yellow squash", tr: "🫘 Sarı Kabak" }, name: { en: "Yellow squash", tr: "Sarı Kabak" } },
  { label: { en: "🍾 Yellow mustard", tr: "🍾 Klasik Sarı Hardal" }, name: { en: "Yellow mustard", tr: "Sarı Hardal" } },
  { label: { en: "🌾 Yeast", tr: "🌾 Maya" }, name: { en: "Yeast", tr: "Maya" } },
  { label: { en: "🥒 Zucchini", tr: "🥒 Kabak" }, name: { en: "Zucchini", tr: "Kabak" } }
];

// ============================================================================
// 3. BACKBONE CATEGORY STRUCTURAL GROUPS (Bilingual header mappings)
// ============================================================================
export const GROCERY_CATALOG = {
  fruits: { 
      keywords: ['apple', 'banana', 'berr', 'strawberry', 'blueberry', 'raspberry', 'citrus', 'lemon', 'lime', 'orange', 'melon', 'watermelon', 'avocado', 'grape', 'peach', 'cherry', 'kiwi', 'mango', 'elma', 'muz', 'çilek', 'böğürtlen', 'portakal', 'limon', 'kavun', 'karpuz', 'üzüm', 'şeftali', 'kiraz', 'kivi'], 
      cat: { en: "Fresh Produce", tr: "Taze Sebze & Meyve" }, 
      sub: { en: "Fruits", tr: "Meyveler" } 
  },
  vegetables: { 
      keywords: ['green bean', 'lettuce', 'spinach', 'potato', 'carrot', 'broccoli', 'tomato', 'onion', 'garlic', 'cucumber', 'pepper', 'corn', 'mushroom', 'cabbage', 'zucchini', 'eggplant', 'marul', 'ispanak', 'patates', 'havuç', 'brokoli', 'domates', 'soğan', 'sarımsak', 'salatalık', 'biber', 'mısır', 'mantar', 'lahana', 'kabak', 'patlıcan'], 
      cat: { en: "Fresh Produce", tr: "Taze Sebze & Meyve" }, 
      sub: { en: "Vegetables", tr: "Sebzeler" } 
  },
  poultry: { 
      keywords: ['chicken', 'turkey', 'wing', 'drumstick', 'breast', 'tavuk', 'hindi', 'kanat', 'baget', 'göğüs'], 
      cat: { en: "🥩 Meat, Seafood & Deli", tr: "🥩 Et, Tavuk & Şarküteri" }, 
      sub: { en: "Meat & Poultry", tr: "Kırmızı & Beyaz Et" } 
  },
  redmeat: { 
      keywords: ['beef', 'pork', 'lamb', 'steak', 'mince', 'rib', 'chop', 'meat patty', 'burger', 'dana', 'sığır', 'biftek', 'kıyma', 'kuzu', 'köfte'], 
      cat: { en: "🥩 Meat, Seafood & Deli", tr: "🥩 Et, Tavuk & Şarküteri" }, 
      sub: { en: "Meat & Poultry", tr: "Kırmızı & Beyaz Et" } 
  },
  seafood: { 
      keywords: ['salmon', 'shrimp', 'cod', 'tuna', 'fish', 'prawn', 'crab', 'lobster', 'somon', 'karides', 'balık', 'midye', 'yengeç'], 
      cat: { en: "🥩 Meat, Seafood & Deli", tr: "🥩 Et, Tavuk & Şarküteri" }, 
      sub: { en: "Fish & Seafood", tr: "Balık & Deniz Ürünleri" } 
  },
  deli: { 
      keywords: ['salami', 'ham', 'bacon', 'sausage', 'pepperoni', 'pastrami', 'olive', 'salam', 'jambon', 'sosis', 'sucuk', 'pastırma', 'zeytin'], 
      cat: { en: "🥩 Meat, Seafood & Deli", tr: "🥩 Et, Tavuk & Şarküteri" }, 
      sub: { en: "Deli", tr: "Meze & Şarküteri" } 
  },
  dairyBase: { 
      keywords: ['milk', 'butter', 'cream', 'sour cream', 'yogurt', 'ayran', 'cacik', 'süt', 'tereyağı', 'krema', 'yoğurt', 'ayran', 'cacık'], 
      cat: { en: "🧀 Dairy & Refrigerated", tr: "🧀 Süt Ürünleri & Dolap" }, 
      sub: { en: "Dairy", tr: "Süt ve Krema" } 
  },
  eggsItem: { 
      keywords: ['egg', 'yumurta'], 
      cat: { en: "🧀 Dairy & Refrigerated", tr: "🧀 Süt Ürünleri & Dolap" }, 
      sub: { en: "Dairy", tr: "Yumurta" } 
  },
  cheeseItem: { 
      keywords: ['cheese', 'cheddar', 'mozzarella', 'feta', 'kasar', 'peynir'], 
      cat: { en: "🧀 Dairy & Refrigerated", tr: "🧀 Süt Ürünleri & Dolap" }, 
      sub: { en: "Cheese", tr: "Peynir Çeşitleri" } 
  },
  veganDairy: { 
      keywords: ['almond milk', 'oat milk', 'soy milk', 'vegan cheese', 'badem sütü', 'yulaf sütü', 'soya sütü'], 
      cat: { en: "🧀 Dairy & Refrigerated", tr: "🧀 Süt Ürünleri & Dolap" }, 
      sub: { en: "Plant-Based Alternatives", tr: "Bitkisel / Vegan Alternatifler" } 
  },
  grains: { 
      keywords: ['rice', 'oat', 'quinoa', 'bread', 'tortilla', 'flour', 'baking', 'yeast', 'sugar', 'powder', 'pirinç', 'yulaf', 'kinoa', 'ekmek', 'lavaş', 'un', 'maya', 'şeker', 'nişasta'], 
      cat: { en: "🥫 Center Store (Pantry Staples)", tr: "🥫 Temel Gıda Kiler Ürünleri" }, 
      sub: { en: "Grains & Baking", tr: "Unlu Mamüller & Karışımlar" } 
  },
  pasta: { 
      keywords: ['pasta', 'spaghetti', 'macaroni', 'noodle', 'makarna', 'spagetti', 'erişte'], 
      cat: { en: "🥫 Center Store (Pantry Staples)", tr: "🥫 Temel Gıda Kiler Ürünleri" }, 
      sub: { en: "Grains & Pasta", tr: "Makarna & Mantı" } 
  },
  canned: { 
      keywords: ['soup', 'bean', 'tomato paste', 'tomato sauce', 'canned', 'çorba', 'fasulye', 'salça', 'konserve'], 
      cat: { en: "🥫 Center Store (Pantry Staples)", tr: "🥫 Temel Gıda Kiler Ürünleri" }, 
      sub: { en: "Canned Goods", tr: "Konserveler" } 
  },
  condiments: { 
      keywords: ['oil', 'olive oil', 'vinegar', 'mayo', 'ketchup', 'mustard', 'hot sauce', 'bbq sauce', 'salt', 'black pepper', 'spice', 'yağ', 'zeytinyağı', 'sirke', 'mayonez', 'ketçap', 'hardal', 'acı sos', 'tuz', 'karabiber', 'baharat'], 
      cat: { en: "🥫 Center Store (Pantry Staples)", tr: "🥫 Temel Gıda Kiler Ürünleri" }, 
      sub: { en: "Condiments & Spices", tr: "Soslar & Baharatlar" } 
  },
  snacks: { 
      keywords: ['chip', 'nut', 'popcorn', 'cracker', 'cookie', 'chocolate', 'biscuit', 'sweet', 'candy', 'cips', 'kuruyemiş', 'çerez', 'mısır', 'kraker', 'kurabiye', 'çikolata', 'bisküvi', 'tatlı', 'şeker'], 
      cat: { en: "🥫 Center Store (Pantry Staples)", tr: "🥫 Temel Gıda Kiler Ürünleri" }, 
      sub: { en: "Snacks", tr: "Atıştırmalıklar" } 
  },
  frozenMeals: { 
      keywords: ['pizza', 'burrito', 'nugget', 'frozen meal', 'waffle', 'dondurulmuş'], 
      cat: { en: "🧊 Frozen Foods", tr: "🧊 Dondurulmuş Gıdalar" }, 
      sub: { en: "Frozen Meals", tr: "Hazır Yemekler" } 
  },
  frozenProduce: { 
      keywords: ['frozen vegetable', 'frozen fruit', 'frozen berry', 'peas', 'bezelye'], 
      cat: { en: "🧊 Frozen Foods", tr: "🧊 Dondurulmuş Gıdalar" }, 
      sub: { en: "Frozen Produce", tr: "Sebze & Meyve" } 
  },
  frozenTreats: { 
      keywords: ['ice cream', 'popsicle', 'sorbet', 'dondurma'], 
      cat: { en: "🧊 Frozen Foods", tr: "🧊 Dondurulmuş Gıdalar" }, 
      sub: { en: "Frozen Treats", tr: "Tatlılar & Dondurmalar" } 
  },
  hotDrinks: { 
      keywords: ['coffee', 'bean', 'tea', 'cai', 'espresso', 'hot chocolate', 'kahve', 'çay', 'sıcak çikolata'], 
      cat: { en: "☕ Beverages", tr: "☕ İçecekler" }, 
      sub: { en: "Hot Drinks", tr: "Sıcak İçecekler" } 
  },
  coldDrinks: { 
      keywords: ['water', 'juice', 'soda', 'cola', 'sprite', 'fanta', 'sports drink', 'energy drink', 'su', 'meyve suyu', 'gazoz', 'kola', 'enerji içeceği'], 
      cat: { en: "☕ Beverages", tr: "☕ İçecekler" }, 
      sub: { en: "Cold Drinks", tr: "Soğuk İçecekler" } 
  },
  alcohol: { 
      keywords: ['beer', 'wine', 'spirit', 'vodka', 'whiskey', 'raki', 'bira', 'şarap', 'votka', 'viski', 'rakı'], 
      cat: { en: "☕ Beverages", tr: "☕ İçecekler" }, 
      sub: { en: "Alcohol", tr: "Alkollü İçecekler" } 
  },
  paper: { 
      keywords: ['toilet paper', 'paper towel', 'napkin', 'tissue', 'tuvalet kağıdı', 'kağıt havlu', 'peçete', 'mendil'], 
      cat: { en: "🧻 Non-Food & Household", tr: "🧻 Temizlik & Ev İhtiyaçları" }, 
      sub: { en: "Paper Products", tr: "Kağıt Ürünleri" } 
  },
  cleaning: { 
      keywords: ['soap', 'detergent', 'spray', 'cleaner', 'bleach', 'sponge', 'sabun', 'deterjan', 'sprey', 'temizleyici', 'çamaşır suyu', 'sünger'], 
      cat: { en: "🧻 Non-Food & Household", tr: "🧻 Temizlik & Ev İhtiyaçları" }, 
      sub: { en: "Cleaning Supplies", tr: "Temizlik Malzemeleri" } 
  },
  personal: { 
      keywords: ['shampoo', 'toothpaste', 'deodorant', 'bandage', 'medicine', 'vitamin', 'brush', 'şampuan', 'diş macunu', 'ilaç', 'vitamin', 'fırça'], 
      cat: { en: "🧻 Non-Food & Household", tr: "🧻 Temizlik & Ev İhtiyaçları" }, 
      sub: { en: "Personal & Health Care", tr: "Kişisel Bakım & Sağlık" } 
  },
  pet: { 
      keywords: ['cat food', 'dog food', 'pet', 'treats', 'kedi maması', 'köpek maması', 'ödül maması'], 
      cat: { en: "🧻 Non-Food & Household", tr: "🧻 Temizlik & Ev İhtiyaçları" }, 
      sub: { en: "Pet Supplies", tr: "Evcil Hayvan Ürünleri" } 
  }
};